Repository flarum/framework, pull requests merged in 2021-09, with the labels that each got.

#3065 fix: Unable to use permission grid dropdowns
  less/admin/PermissionsPage.less
Labels: type/bug

#3016 [A11Y] Adds missing focus rings back to control elements
  less/common/Button.less
  less/common/Dropdown.less
  less/common/FormControl.less
  less/common/Search.less
  views/layouts/basic.blade.php
Labels: type/accessibility

#3017 [A11Y] Accessibility improvements for the Search component
  js/src/forum/components/Search.tsx
  less/common/Search.less
  less/common/mixins/accessibility.less
  locale/core.yml
Labels: type/accessibility

#3057 Preload FontAwesome, JS and CSS
  src/Extend/Frontend.php
  src/Frontend/Document.php
  src/Frontend/FrontendServiceProvider.php
  tests/integration/extenders/FrontendPreloadTest.php
Labels: type/feature, type/performance
