Repository flarum/framework, pull requests merged in 2021-12, with the labels that each got.

#3186 Move colorItems to ItemList
  js/src/admin/components/AppearancePage.js
Labels: type/extensibility

#3189 Make StatusWidget tools dropdown extensible
  js/src/admin/components/StatusWidget.js
Labels: type/extensibility

#3190 feat: add Less custom function extender, `is-extension-enabled` function
  src/Extend/Theme.php
  src/Frontend/Assets.php
  src/Frontend/Compiler/LessCompiler.php
  src/Frontend/FrontendServiceProvider.php
  tests/fixtures/less/custom_function.less
  tests/integration/extenders/ThemeTest.php
Labels: type/feature, type/extensibility

#3206 fix: replace throw with debug warning to fix breaking change
  js/src/common/Store.ts
Labels: type/regression

#3207 fix: Add a11y labels to auth modal inputs
  js/src/forum/components/ForgotPasswordModal.tsx
  js/src/forum/components/LogInModal.tsx
  js/src/forum/components/SignUpModal.tsx
Labels: type/accessibility

#3167 feat/fix: allow replacing of blade template namespaces
  src/Extend/View.php
  tests/fixtures/views/override/frontend/app.blade.php
  tests/integration/extenders/ViewTest.php
Labels: type/feature, type/extensibility

#3212 fix: breaking change in Search component - renaming of `state` property
  js/src/common/Store.ts
  js/src/common/helpers/fireDebugWarning.ts
  js/src/common/utils/evented.js
  js/src/forum/components/Search.tsx
Labels: type/regression

#3211 docs: fix broken contribution link in README; add screenshot
  README.md
Labels: documentation

#3219 fix: hide `WelcomeHero` when content is empty
  js/src/forum/components/WelcomeHero.js
  js/src/forum/components/WelcomeHero.tsx
Labels: type/bug

#3226 fix: incorrect return type on `pushPayload`
  js/src/common/Store.ts
Labels: type/regression

#3214 1.2 JS clean-up
  js/src/admin/components/AdminNav.js
  js/src/admin/components/BasicsPage.js
  js/src/admin/components/DashboardWidget.js
  js/src/admin/components/HeaderPrimary.js
  js/src/admin/components/HeaderSecondary.js
  js/src/admin/components/UploadImageButton.js
  js/src/common/Application.tsx
  js/src/common/Fragment.ts
  js/src/common/components/Checkbox.js
  js/src/common/components/Dropdown.js
  js/src/common/components/LinkButton.js
  js/src/common/components/Navigation.js
  js/src/common/components/SplitDropdown.js
  js/src/common/components/TextEditor.js
  js/src/common/extend.ts
  js/src/common/helpers/punctuateSeries.js
  js/src/common/states/AlertManagerState.ts
  js/src/common/states/ModalManagerState.ts
  js/src/common/states/PageState.js
  js/src/common/utils/Drawer.js
  js/src/common/utils/ItemList.ts
  js/src/common/utils/ScrollListener.js
  js/src/common/utils/anchorScroll.js
  js/src/common/utils/computed.ts
  js/src/common/utils/evented.js
  js/src/common/utils/mixin.js
  js/src/forum/components/AvatarEditor.js
  js/src/forum/components/CommentPost.js
  js/src/forum/components/Composer.js
  js/src/forum/components/ComposerBody.js
  js/src/forum/components/DiscussionComposer.js
  js/src/forum/components/DiscussionHero.js
  js/src/forum/components/DiscussionListItem.js
  js/src/forum/components/DiscussionPage.tsx
  js/src/forum/components/EditPostComposer.js
  js/src/forum/components/EventPost.js
  js/src/forum/components/HeaderPrimary.js
  js/src/forum/components/IndexPage.js
  js/src/forum/components/LogInButtons.js
  js/src/forum/components/Notification.js
  js/src/forum/components/NotificationGrid.js
  js/src/forum/components/Post.js
  js/src/forum/components/PostMeta.js
  js/src/forum/components/PostStream.js
  js/src/forum/components/PostStreamScrubber.js
  js/src/forum/components/PostsUserPage.js
  js/src/forum/components/ReplyComposer.js
  js/src/forum/components/SessionDropdown.js
  js/src/forum/components/SettingsPage.js
  js/src/forum/components/SignUpModal.tsx
  js/src/forum/components/UserCard.js
  js/src/forum/components/UserPage.js
  js/src/forum/states/ComposerState.js
  js/src/forum/states/PostStreamState.js
  js/src/forum/utils/DiscussionControls.js
  js/src/forum/utils/Pane.js
  js/src/forum/utils/PostControls.js
  js/src/forum/utils/UserControls.js
  js/src/forum/utils/alertEmailConfirmation.js
  js/src/forum/utils/slidable.js
Labels: type/cleanup

#3230 perf: only update last seen time when current > 120s ago
  src/Http/AccessToken.php
  src/User/User.php
  tests/integration/api/users/UpdateTest.php
Labels: needs-discussion, type/performance

#3233 perf: include request info in first accesstoken touch
  src/Http/Middleware/RememberFromCookie.php
Labels: type/performance

#3235 fix: mark render method in RouteResolver as optional
  js/src/common/Application.tsx
Labels: type/regression

#3236 fix: don't fire deprecation warnings for Mithril-originating action
  js/src/forum/components/Search.tsx
Labels: type/regression

#3237 fix(a11y): fix a11y warning in alert, and other a11y fixes
  js/src/common/components/Alert.tsx
  js/src/common/components/AlertManager.js
  locale/core.yml
Labels: type/accessibility

#3239 fix: error in funding `composer.json` block bricks frontend
  src/Extension/Extension.php
Labels: type/bug

#3243 fix: `Until reply` renaming permission of discussions broken in php 8
  src/Discussion/Access/DiscussionPolicy.php
  tests/integration/policy/DiscussionPolicyTest.php
  tests/integration/policy/PostPolicyTest.php
Labels: type/bug
