Repository flarum/framework, pull requests merged in 2021-08, with the labels that each got.

#3015 Update Normalize.css to v8.0.1
  less/common/normalize.less
Labels: type/cleanup

#2887 Permission Grid: stick the headers to handle a lot of tags
  js/src/admin/components/PermissionGrid.js
  less/admin/PermissionsPage.less
Labels: javascript

#3027 [A11Y] Explicitly state `aria-hidden` value; hide icons from screenreaders
  js/src/admin/components/UserListPage.tsx
  js/src/common/components/LoadingIndicator.tsx
  js/src/common/helpers/icon.tsx
Labels: type/accessibility

#3014 [A11Y] Make checkboxes focusable
  js/src/common/components/Checkbox.js
  less/common/Checkbox.less
  less/common/mixins/accessibility.less
  less/common/scaffolding.less
Labels: type/accessibility

#3032 Remove format hook on commit; update CI to only build with valid formatting
  .github/workflows/build.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  js/package-lock.json
  js/package.json
Labels: type/infrastructure

#3004 Use ItemList for DiscussionPage content
  js/src/forum/components/DiscussionPage.js
Labels: type/extensibility

#3026 CSS Code Housekeeping
  less/admin/AdminNav.less
  less/admin/ExtensionPage.less
  less/admin/ExtensionWidget.less
  less/admin/PermissionsPage.less
  less/common/Alert.less
  less/common/AlertManager.less
  less/common/App.less
  less/common/Avatar.less
  less/common/Badge.less
  less/common/Button.less
  less/common/Checkbox.less
  less/common/Dropdown.less
  less/common/FormControl.less
  less/common/LoadingIndicator.less
  less/common/Modal.less
  less/common/Navigation.less
  less/common/Search.less
  less/common/Tooltip.less
  less/common/mixins/header-background.less
  less/common/mixins/vendor-prefixes.less
  less/common/scaffolding.less
  less/forum/Composer.less
  less/forum/DiscussionPage.less
  less/forum/NotificationsDropdown.less
  less/forum/Post.less
  less/forum/PostStream.less
  less/forum/SignUpModal.less
  less/forum/Slidable.less
  less/forum/UserCard.less
Labels: type/cleanup, type/theming

#2984 Rewrite Button to Typescript
  js/src/common/components/Button.js
  js/src/common/components/Button.tsx
  js/src/common/components/TextEditorButton.js
  js/src/common/helpers/fireDebugWarning.ts
Labels: type/cleanup, type/accessibility
