Repository flarum/framework, pull requests merged in 2021-04, with the labels that each got.

#2760 Replace `classList` with `clsx` library
  js/package-lock.json
  js/package.json
  js/src/common/utils/classList.js
  js/src/common/utils/classList.ts
Labels: dependencies, type/cleanup

#2766 Remove unneeded vendor prefixes
  js/src/forum/components/PostStreamScrubber.js
  less/common/mixins/vendor-prefixes.less
  less/forum/Scrubber.less
Labels: type/cleanup

#2753 Bump dependencies, add missing typing libraries
  js/package-lock.json
  js/package.json
  js/shims.d.ts
  js/src/common/Component.ts
  js/src/common/index.js
  js/src/forum/index.js
  js/webpack.config.js
Labels: dependencies, type/cleanup

#2764 Replace spin.js with a CSS-only loading spinner
  js/src/common/components/LoadingIndicator.js
  js/src/common/components/LoadingIndicator.tsx
  less/common/Checkbox.less
  less/common/LoadingIndicator.less
  less/forum/ActivityPage.less
  less/forum/DiscussionList.less
Labels: type/cleanup

#2410 Access request actor in error handler
  src/Admin/AdminServiceProvider.php
  src/Api/ApiServiceProvider.php
  src/Forum/ForumServiceProvider.php
  src/Http/ActorReference.php
  src/Http/Middleware/InjectActorReference.php
  src/Http/RequestUtil.php
Labels: org/keep

#2799 Add accessibility attributes to loading spinner
  js/src/common/components/LoadingIndicator.tsx
  locale/core.yml
Labels: type/accessibility

#2797 Fix uses of loading spinner
  js/src/common/components/Button.js
  js/src/common/components/Checkbox.js
  js/src/common/components/LoadingIndicator.tsx
  js/src/forum/components/AvatarEditor.js
  js/src/forum/components/ComposerBody.js
  js/src/forum/components/DiscussionList.js
  js/src/forum/components/DiscussionPage.js
  js/src/forum/components/NotificationList.js
  js/src/forum/components/Search.js
  js/src/forum/components/UserPage.js
  less/common/Button.less
  less/common/LoadingIndicator.less
  less/common/Search.less
  less/forum/AvatarEditor.less
  less/forum/Composer.less
Labels: type/bug

#2626 Add users list to admin dashboard
  js/src/admin/compat.js
  js/src/admin/components/AdminNav.js
  js/src/admin/components/UserListPage.tsx
  js/src/admin/routes.js
  js/src/common/compat.js
  js/src/common/components/EditUserModal.js
  js/src/forum/compat.js
  js/src/forum/utils/UserControls.js
  less/admin.less
  less/admin/UsersListPage.less
  less/common/EditUserModal.less
  less/common/common.less
  less/forum.less
  locale/core.yml
  src/Admin/Content/AdminPayload.php
Labels: prio/high

#2814 [A11Y] Add focus ring mixin to restore ring to elements which no longer have it
  less/common/mixins.less
  less/common/mixins/accessibility.less
Labels: type/accessibility
