Repository flarum/framework, pull requests merged in 2021-11, with the labels that each got.

#3116 Allow using callbacks with `load` relations extender
  src/Api/Controller/AbstractSerializeController.php
  src/Api/Controller/ListDiscussionsController.php
  src/Api/Controller/ListGroupsController.php
  src/Api/Controller/ListNotificationsController.php
  src/Api/Controller/ListPostsController.php
  src/Api/Controller/ListUsersController.php
  src/Extend/ApiController.php
  tests/integration/extenders/ApiControllerTest.php
Labels: type/performance

#3149 chore: replace `for ... in` with `Array.reduce`
  js/src/forum/components/IndexPage.js
Labels: type/cleanup

#3148 fix: Component.component argument typings
  js/src/common/Component.ts
Labels: type/cleanup

#2928 Convert extend util to TypeScript
  js/src/@types/global.d.ts
  js/src/common/Application.tsx
  js/src/common/compat.js
  js/src/common/extend.ts
  js/src/common/utils/proxifyCompat.ts
Labels: type/cleanup

#3109 feat: Use an extensible document title driver implementation
  src/Extend/Frontend.php
  src/Frontend/Document.php
  src/Frontend/Driver/BasicTitleDriver.php
  src/Frontend/Driver/TitleDriverInterface.php
  src/Frontend/FrontendServiceProvider.php
  src/helpers.php
  tests/integration/extenders/FrontendTitleTest.php
Labels: type/feature

#3147 feat: allow use of any tag in `listItems` helper
  js/src/common/helpers/listItems.tsx
Labels: type/feature, needs-discussion

#3132 chore: better typings for DiscussionListState
  js/src/forum/states/DiscussionListState.ts
Labels: type/cleanup

#3155 chore: migrate fully to Yarn
  .github/workflows/js.yml
  .gitignore
  js/.gitignore
  js/.yarn/releases/yarn-3.1.0.cjs
  js/.yarnrc.yml
  js/package-lock.json
  js/package.json
  js/webpack.config.js
  js/yarn.lock
Labels: type/feature

#3005 Rewrite ItemList; update ItemList typings
  js/src/@types/global.d.ts
  js/src/admin/components/UserListPage.tsx
  js/src/common/compat.js
  js/src/common/utils/ItemList.ts
  js/src/common/utils/isObject.ts
Labels: type/bug, type/cleanup

#3161 Add 'Close' & 'Back' aria-label attributes to buttons.
  js/src/common/components/Modal.tsx
  js/src/common/components/Navigation.js
  js/src/forum/components/WelcomeHero.js
  locale/core.yml
Labels: type/accessibility

#3018 [A11Y] Add focus traps to modals and nav drawer
  js/package.json
  js/src/common/compat.js
  js/src/common/components/ModalManager.tsx
  js/src/common/utils/Drawer.js
  js/src/common/utils/focusTrap.ts
  js/src/forum/components/Search.tsx
  js/src/forum/utils/KeyboardNavigatable.ts
  js/yarn.lock
  less/common/root.less
Labels: type/accessibility

#3173 fix(a11y): show post action items when focus is within the post
  less/forum/Post.less
Labels: type/bug, type/accessibility

#2929 Convert some common classes/utils to TS
  js/src/common/Session.js
  js/src/common/Session.ts
  js/src/common/states/AlertManagerState.ts
  js/src/common/utils/extractText.ts
Labels: type/cleanup
