Repository flarum/framework, pull requests merged in 2022-09, with the labels that each got.

#3621 fix: post query wildcard selection causes ambiguity
  framework/core/src/Post/Filter/PostFilterer.php
Labels: type/bug, prio/high

#3619 fix(regression): bad post actions alignment introduced in #3540
  framework/core/less/forum/DiscussionPage.less
  framework/core/less/forum/Post.less
Labels: type/bug, type/regression, prio/high

#3616 fix: password reset leaks user existence
  framework/core/locale/core.yml
  framework/core/src/Api/Controller/ForgotPasswordController.php
  framework/core/src/User/Command/RequestPasswordReset.php
  framework/core/src/User/Command/RequestPasswordResetHandler.php
  framework/core/src/User/Job/RequestPasswordResetJob.php
  framework/core/tests/integration/api/users/SendPasswordResetEmailTest.php
Labels: security

#3610 feat: customizable session driver
  framework/core/src/Extend/Session.php
  framework/core/src/Foundation/Console/InfoCommand.php
  framework/core/src/User/SessionDriverInterface.php
  framework/core/src/User/SessionManager.php
  framework/core/src/User/SessionServiceProvider.php
  framework/core/tests/integration/extenders/SessionTest.php
  php-packages/testing/src/integration/TestCase.php
Labels: type/feature

#3650 feat: replace `ColorPreviewInput` for GroupModal color input
  framework/core/js/src/admin/components/EditGroupModal.tsx
Labels: type/feature

#3622 feat(statistics): support for custom date ranges
  extensions/statistics/js/package.json
  extensions/statistics/js/src/admin/components/StatisticsWidget.tsx
  extensions/statistics/js/src/admin/components/StatisticsWidgetDateSelectionModal.tsx
  extensions/statistics/less/admin.less
  extensions/statistics/locale/en.yml
  extensions/statistics/src/Api/Controller/ShowStatisticsData.php
  extensions/statistics/tests/integration/api/CanRequestCustomTimedStatisticsTest.php
  extensions/statistics/tests/integration/api/CanRequestLifetimeStatisticsTest.php
  extensions/statistics/tests/integration/api/CanRequestTimedStatisticsTest.php
Labels: type/feature
