Repository flarum/framework, pull requests merged in 2022-04, with the labels that each got.

#3382 fix: Check for null before attempting ->getRelations()
  extensions/mentions/src/Formatter/FormatUserMentions.php
  extensions/mentions/src/Formatter/UnparseUserMentions.php
Labels: type/extensibility

#3385 fix: languages with combining characters cannot be searched
  framework/core/src/Discussion/Search/Gambit/FulltextGambit.php
  framework/core/tests/integration/api/discussions/ListWithFulltextSearchTest.php
Labels: type/bug

#3387 fix: slug transliteration assuming the language is always `en`
  framework/core/src/Discussion/Discussion.php
  framework/core/tests/integration/api/discussions/CreateTest.php
Labels: type/i18n

#3384 fix: php8.1 deprecation warnings
  framework/core/composer.json
  framework/core/src/Foundation/Config.php
Labels: dependencies

#3354 fix: don't duplicate path in URL to post on subdirectory installs.
  framework/core/js/src/forum/components/PostMeta.js
  framework/core/src/Api/Serializer/ForumSerializer.php
Labels: type/bug
