Repository flarum/framework, pull requests merged in 2022-12, with the labels that each got.

#3588 feat: allow using utf8 characters in tag slugs
  extensions/tags/extend.php
  extensions/tags/src/Api/Controller/ShowTagController.php
  extensions/tags/src/Api/Serializer/TagSerializer.php
  extensions/tags/src/Content/Tag.php
  extensions/tags/src/Query/TagFilterGambit.php
  extensions/tags/src/TagRepository.php
  extensions/tags/src/Utf8SlugDriver.php
  extensions/tags/tests/integration/api/discussions/ListTest.php
  extensions/tags/tests/integration/api/tags/ListTest.php
  extensions/tags/tests/integration/api/tags/ShowTest.php
  framework/core/js/src/common/utils/string.ts
Labels: type/feature, type/i18n

#3686 feat(tags): admin tag selection component (reusable tag selection modal)
  extensions/emoji/js/src/forum/addComposerAutocomplete.js
  extensions/mentions/js/src/forum/addComposerAutocomplete.js
  extensions/tags/js/src/@types/shims.d.ts
  extensions/tags/js/src/admin/addTagSelectionSettingComponent.tsx
  extensions/tags/js/src/admin/addTagsPermissionScope.tsx
  extensions/tags/js/src/admin/components/SelectTagsSettingComponent.tsx
  extensions/tags/js/src/admin/components/TagsPage.js
  extensions/tags/js/src/admin/index.ts
  extensions/tags/js/src/common/compat.js
  extensions/tags/js/src/common/components/TagSelectionModal.tsx
  extensions/tags/js/src/common/states/TagListState.ts
  extensions/tags/js/src/forum/components/TagDiscussionModal.tsx
  extensions/tags/js/src/forum/index.ts
  extensions/tags/less/common/TagSelectionModal.less
  extensions/tags/less/common/common.less
  extensions/tags/less/forum.less
  extensions/tags/locale/en.yml
  framework/core/js/src/common/compat.ts
  framework/core/js/src/common/components/Modal.tsx
  framework/core/js/src/common/utils/KeyboardNavigatable.ts
  framework/core/js/src/forum/compat.ts
  framework/core/js/src/forum/components/Search.tsx
Labels: type/feature, javascript, type/extensibility, needs-documentation

#3706 fix: 3 digit hex color value in color input not supported
  framework/core/js/src/common/components/ColorPreviewInput.tsx
Labels: type/bug, javascript
