Repository flarum/framework, pull requests merged in 2022-08, with the labels that each got.

#3565 feat: Restart the queue worker after cache clearing, ext enable/disable, save settings
  framework/core/src/Queue/QueueRestarter.php
  framework/core/src/Queue/QueueServiceProvider.php
Labels: type/feature

#3575 fix: sticky nav content displays below post stream
  framework/core/less/forum/DiscussionPage.less
Labels: type/bug, type/regression, prio/high

#3576 feat: add createTableIfNotExists migration helper
  framework/core/src/Database/Migration.php
Labels: type/extensibility

#3577 chore(approval, likes): use subscribers
  extensions/approval/extend.php
  extensions/approval/src/Listener/ApproveContent.php
  extensions/approval/src/Listener/UnapproveNewContent.php
  extensions/likes/extend.php
  extensions/likes/src/Listener/SaveLikesToDatabase.php
Labels: type/cleanup

#3549 fix: intellisense imports defaulting to absolute path from `src` folder
  extensions/akismet/js/tsconfig.json
  extensions/flags/js/tsconfig.json
  extensions/package-manager/js/tsconfig.json
  extensions/pusher/js/tsconfig.json
  extensions/statistics/js/tsconfig.json
  extensions/tags/js/tsconfig.json
  js-packages/tsconfig/README.md
Labels: type/bug

#3456 feat(modals): support stacking modals, remove bootstrap modals dependency
  framework/core/js/package.json
  framework/core/js/src/common/Application.tsx
  framework/core/js/src/common/components/Modal.tsx
  framework/core/js/src/common/components/ModalManager.tsx
  framework/core/js/src/common/index.ts
  framework/core/js/src/common/states/ModalManagerState.ts
  framework/core/less/common/Modal.less
  yarn.lock
Labels: type/feature, type/cleanup, type/accessibility

#3573 chore: unify JS actions into one (rewritten `flarum/action-build`)
  .github/workflows/REUSABLE_frontend.yml
  .github/workflows/flarum-akismet-frontend.yml
  .github/workflows/flarum-approval-frontend.yml
  .github/workflows/flarum-core-frontend.yml
  .github/workflows/flarum-embed-frontend.yml
  .github/workflows/flarum-emoji-frontend.yml
  .github/workflows/flarum-likes-frontend.yml
  .github/workflows/flarum-lock-frontend.yml
  .github/workflows/flarum-markdown-frontend.yml
  .github/workflows/flarum-mentions-frontend.yml
  .github/workflows/flarum-nicknames-frontend.yml
  .github/workflows/flarum-package-manager-frontend.yml
  .github/workflows/flarum-pusher-frontend.yml
  .github/workflows/flarum-statistics-frontend.yml
  .github/workflows/flarum-sticky-frontend.yml
  .github/workflows/flarum-subscriptions-frontend.yml
  .github/workflows/flarum-suspend-frontend.yml
  .github/workflows/flarum-tags-frontend.yml
  .github/workflows/frontend.yml
  extensions/akismet/js/package.json
  extensions/akismet/js/tsconfig.json
  extensions/emoji/js/package.json
  extensions/flags/js/package.json
  extensions/flags/js/tsconfig.json
  extensions/lock/js/package.json
  extensions/package-manager/js/package.json
  extensions/package-manager/js/tsconfig.json
  extensions/pusher/js/package.json
  extensions/pusher/js/tsconfig.json
  extensions/statistics/js/package.json
  extensions/statistics/js/tsconfig.json
  extensions/tags/js/package.json
  extensions/tags/js/tsconfig.json
Labels: type/infrastructure

#3529 feat: Delete all notifications
  framework/core/js/src/forum/components/NotificationList.js
  framework/core/js/src/forum/states/NotificationListState.ts
  framework/core/less/forum/NotificationList.less
  framework/core/locale/core.yml
  framework/core/src/Api/Controller/DeleteAllNotificationsController.php
  framework/core/src/Api/routes.php
  framework/core/src/Notification/Command/DeleteAllNotifications.php
  framework/core/src/Notification/Command/DeleteAllNotificationsHandler.php
  framework/core/src/Notification/Event/DeletedAll.php
  framework/core/src/Notification/NotificationRepository.php
  framework/core/tests/integration/api/notifications/DeleteTest.php
Labels: type/feature

#3538 refactor: convert page components to TypeScript
  framework/core/js/src/admin/AdminApplication.ts
  framework/core/js/src/admin/components/AdminPage.tsx
  framework/core/js/src/admin/components/AppearancePage.tsx
  framework/core/js/src/admin/components/BasicsPage.tsx
  framework/core/js/src/admin/components/ExtensionPage.tsx
  framework/core/js/src/admin/components/MailPage.tsx
  framework/core/js/src/admin/components/PermissionsPage.tsx
  framework/core/js/src/forum/components/NotificationsPage.tsx
  framework/core/js/src/forum/components/SettingsPage.tsx
  framework/core/locale/core.yml
Labels: type/cleanup

#3590 feat: Admin debug mode warning
  framework/core/js/src/admin/components/DashboardPage.tsx
  framework/core/js/src/admin/components/DebugWarningWidget.tsx
  framework/core/js/src/common/components/Alert.tsx
  framework/core/less/admin.less
  framework/core/less/admin/DebugWarningWidget.less
  framework/core/less/common/Alert.less
  framework/core/locale/core.yml
  framework/core/src/Admin/Content/AdminPayload.php
Labels: type/feature

#3595 test: refactor prefix matrix and add `MySQL 8.0` & `PHP 7.3` to workflows
  .github/workflows/REUSABLE_backend.yml
Labels: type/infrastructure

#3601 perf(statistics): split timed data into per-model XHR requests
  extensions/statistics/js/src/admin/components/StatisticsWidget.tsx
  extensions/statistics/src/Api/Controller/ShowStatisticsData.php
Labels: type/performance

#3606 feat: discussion UTF-8 slug driver
  framework/core/src/Discussion/Discussion.php
  framework/core/src/Discussion/Utf8SlugDriver.php
  framework/core/src/Http/HttpServiceProvider.php
  framework/core/tests/integration/slugger/SlugDriverTest.php
Labels: type/feature

#3615 fix(tags): use default index sortmap
  extensions/tags/src/Content/Tag.php
Labels: type/bug

#3503 feat(subscriptions): add option to send notifications when not caught up
  extensions/subscriptions/extend.php
  extensions/subscriptions/js/forum.ts
  extensions/subscriptions/js/package.json
  extensions/subscriptions/js/src/forum/addSubscriptionSettings.tsx
  extensions/subscriptions/js/tsconfig.json
  extensions/subscriptions/locale/en.yml
  extensions/subscriptions/src/Job/SendReplyNotification.php
  extensions/subscriptions/tests/integration/api/discussions/ReplyNotificationTest.php
  yarn.lock
Labels: type/feature, prio/high

#3584 feat: Add custom class for email confirmation alert
  framework/core/js/src/forum/utils/alertEmailConfirmation.js
Labels: type/feature
