Repository flarum/framework, pull requests merged in 2022-07, with the labels that each got.

#3419 fix: restricted sibling tags appearing for unauthorized members on the sidebar
  extensions/tags/src/Api/Controller/ShowTagController.php
  extensions/tags/src/TagRepository.php
  extensions/tags/tests/integration/api/tags/ListTest.php
  extensions/tags/tests/integration/api/tags/ShowTest.php
Labels: type/bug

#3501 Fix assertAdmin sending wrong ability name to gate
  framework/core/src/User/User.php
Labels: type/bug

#3513 chore: add `.gitattributes` to extensions to export-ignore files.
  extensions/akismet/.gitattributes
  extensions/approval/.gitattributes
  extensions/bbcode/.gitattributes
  extensions/embed/.gitattributes
  extensions/emoji/.gitattributes
  extensions/flags/.gitattributes
  extensions/lang-english/.gitattributes
  extensions/likes/.gitattributes
  extensions/lock/.gitattributes
  extensions/markdown/.gitattributes
  extensions/mentions/.gitattributes
  extensions/nicknames/.gitattributes
  extensions/package-manager/.gitattributes
  extensions/pusher/.gitattributes
  extensions/statistics/.gitattributes
  extensions/sticky/.gitattributes
  extensions/subscriptions/.gitattributes
  extensions/suspend/.gitattributes
  extensions/tags/.gitattributes
Labels: type/cleanup

#3520 fix(a11y): add accessible labels to notification grid options
  framework/core/js/src/forum/components/NotificationGrid.js
  framework/core/locale/core.yml
Labels: type/accessibility

#3521 fix(a11y): set `aria-busy` when editing a post stream item
  framework/core/js/src/forum/components/CommentPost.js
  framework/core/js/src/forum/components/ReplyPlaceholder.js
Labels: type/accessibility

#3522 fix(a11y): present post streams as feeds
  framework/core/js/src/forum/components/PostStream.js
Labels: type/accessibility

#3525 fix: Set the translator locale to user preference for email notifications
  framework/core/src/Notification/NotificationMailer.php
Labels: type/bug

#3530 feat: extender to add custom less variables
  framework/core/src/Extend/Theme.php
  framework/core/src/Frontend/FrontendServiceProvider.php
  framework/core/tests/fixtures/less/custom_variable.less
  framework/core/tests/integration/extenders/ThemeTest.php
Labels: type/feature, type/theming

#3537 fix: replace `.fa()` mixin usage with `.fas()`
  extensions/mentions/less/forum.less
  extensions/tags/less/forum/TagDiscussionModal.less
  framework/core/less/common/Search.less
  framework/core/less/forum/DiscussionListItem.less
Labels: type/cleanup

#3536 refactor: convert `AlertManager` `IndexPage` and `UserPage` components to TS
  framework/core/js/src/admin/compat.ts
  framework/core/js/src/common/compat.ts
  framework/core/js/src/common/components/AlertManager.js
  framework/core/js/src/common/components/AlertManager.tsx
  framework/core/js/src/common/components/Page.tsx
  framework/core/js/src/common/states/AlertManagerState.ts
  framework/core/js/src/forum/compat.ts
  framework/core/js/src/forum/components/DiscussionsUserPage.tsx
  framework/core/js/src/forum/components/IndexPage.tsx
  framework/core/js/src/forum/components/PostsUserPage.tsx
  framework/core/js/src/forum/components/UserPage.tsx
Labels: type/cleanup

#3540 feat: use `position: sticky` for discussion side nav
  framework/core/less/common/App.less
  framework/core/less/common/scaffolding.less
  framework/core/less/forum/DiscussionPage.less
  framework/core/less/forum/Post.less
Labels: type/feature

#3543 fix: unread notifications are globally cached between users.
  framework/core/src/User/User.php
Labels: type/bug

#3534 feat(likes): Option to prevent users liking their own posts
  extensions/likes/extend.php
  extensions/likes/js/src/admin/index.js
  extensions/likes/locale/en.yml
  extensions/likes/src/Access/LikePostPolicy.php
  extensions/likes/tests/integration/api/LikePostTest.php
Labels: type/feature

#3542 fix: html entities shown raw in page title
  framework/core/js/src/common/Application.tsx
  framework/core/views/frontend/app.blade.php
Labels: type/bug

#3550 fix: titles positioned wrongly with custom header height
  framework/core/less/common/App.less
Labels: type/bug

#3564 feat: publish assets on admin dashboard cache clear
  framework/core/js/src/admin/components/StatusWidget.js
  framework/core/locale/core.yml
  framework/core/src/Api/Controller/ClearCacheController.php
  framework/core/src/Foundation/ErrorServiceProvider.php
  framework/core/src/Foundation/IOException.php
Labels: type/bug, type/feature

#3569 fix: incorrect centring of deleted user avatars in notification list
  framework/core/less/forum/NotificationList.less
Labels: type/bug

#3548 fix: potential static caching memory exhaustion
  framework/core/src/User/User.php
Labels: type/cleanup

#3566 feat: expose assets base url to frontend forum model
  framework/core/src/Api/Serializer/ForumSerializer.php
Labels: type/feature, type/extensibility

#3570 chore(tags): Replace event helper with event dispatcher
  extensions/tags/src/Command/CreateTagHandler.php
  extensions/tags/src/Command/DeleteTagHandler.php
  extensions/tags/src/Command/EditTagHandler.php
Labels: type/cleanup
