Repository flarum/framework, pull requests merged in 2022-11, with the labels that each got.

#3662 feat: add statistics chart export button
  extensions/statistics/js/src/admin/components/StatisticsWidget.tsx
  extensions/statistics/less/admin.less
  extensions/statistics/locale/en.yml
Labels: type/feature

#3665 fix: larastan v1 incompatible with phpstan v1.9.0
  composer.json
  php-packages/phpstan/composer.json
Labels: dependencies

#3661 [statistics] fix: add missing last period to custom date ranges
  extensions/statistics/js/src/admin/components/StatisticsWidget.tsx
  extensions/statistics/src/Api/Controller/ShowStatisticsData.php
  extensions/statistics/tests/integration/api/CanRequestCustomTimedStatisticsTest.php
Labels: type/bug

#3660 Fix tag discussion count decreased by 2 when hiding before deleting
  extensions/tags/src/Listener/UpdateTagMetadata.php
Labels: type/bug

#3655 feat: allow specifying extensions when installing an instance
  framework/core/src/Extension/Extension.php
  framework/core/src/Extension/ExtensionManager.php
  framework/core/src/Install/Console/FileDataProvider.php
  framework/core/src/Install/Steps/EnableBundledExtensions.php
Labels: type/extensibility

#3656 feat: send notifications of a new reply when post is approved
  extensions/approval/extend.php
  extensions/approval/src/Listener/ApproveContent.php
  extensions/approval/src/Listener/UpdateDiscussionAfterPostApproval.php
  extensions/subscriptions/composer.json
  extensions/subscriptions/extend.php
  extensions/subscriptions/src/Listener/SendNotificationWhenReplyIsPosted.php
  extensions/subscriptions/tests/integration/api/discussions/ReplyNotificationTest.php
Labels: type/feature

#3670 feat: Allow additional login params, Introduce `LogInValidator`
  framework/core/js/src/forum/components/LogInModal.tsx
  framework/core/src/Forum/Controller/LogInController.php
  framework/core/src/Forum/LogInValidator.php
Labels: type/extensibility

#3671 feat: Allow additional reset password params, introduce `ForgotPasswordValidator`
  framework/core/js/src/forum/components/ForgotPasswordModal.tsx
  framework/core/src/Api/Controller/ForgotPasswordController.php
  framework/core/src/Api/ForgotPasswordValidator.php
Labels: type/extensibility

#3672 fix: groupmentions have poor contrast on some backgrounds
  extensions/mentions/js/src/forum/utils/textFormatter.js
  extensions/mentions/less/forum.less
  extensions/mentions/src/ConfigureMentions.php
  extensions/mentions/tests/integration/api/GroupMentionsTest.php
Labels: type/bug

#3675 fix: post dropdown opens all dropdowns in `.Post-actions`
  framework/core/js/src/forum/components/Post.tsx
  framework/core/less/forum/Post.less
Labels: type/bug

#3593 feat: expose queue driver, schedule status
  framework/core/js/src/admin/components/StatusWidget.js
  framework/core/locale/core.yml
  framework/core/src/Admin/Content/AdminPayload.php
  framework/core/src/Console/ConsoleServiceProvider.php
  framework/core/src/Foundation/ApplicationInfoProvider.php
  framework/core/src/Foundation/Console/InfoCommand.php
  framework/core/src/Foundation/Console/ScheduleRunCommand.php
Labels: type/feature

#3669 chore: Indicate cross-origin request in generic error message
  framework/core/js/src/common/Application.tsx
  framework/core/locale/core.yml
Labels: type/cleanup

#3690 fix: provide web friendly session driver name
  framework/core/src/Admin/Content/AdminPayload.php
  framework/core/src/Foundation/ApplicationInfoProvider.php
Labels: type/regression

#3691 feat: allow push additional items to the end of the poststream
  framework/core/js/src/forum/components/PostStream.js
Labels: javascript, type/extensibility

#3668 feat: include current user as forum relation
  framework/core/src/Api/Controller/ShowForumController.php
  framework/core/src/Api/Serializer/ForumSerializer.php
  framework/core/src/Frontend/Content/CorePayload.php
  framework/core/tests/integration/api/forum/ShowTest.php
Labels: type/feature

#3695 chore: update JS dependencies
  framework/core/js/package.json
  framework/core/js/src/common/Application.tsx
  package.json
  yarn.lock
Labels: type/cleanup, javascript

#3696 fix: column `id` can be ambiguous in group filter with extensions
  framework/core/src/User/Query/GroupFilterGambit.php
Labels: type/extensibility

#3700 fix: undefined showing in dropdown active title
  framework/core/js/src/common/components/SelectDropdown.tsx
Labels: type/regression, javascript
