Repository flarum/framework, pull requests merged in 2022-05, with the labels that each got.

#3414 fix: first posts having `NULL` as value for number column
  .gitignore
  framework/core/src/Post/Post.php
Labels: type/bug, type/regression

#3413 fix: Composer discussion title not visible with certain colors
  framework/core/less/forum/Composer.less
Labels: type/bug

#3412 fix(a11y): Tag selection modal input visibility
  extensions/tags/less/forum/TagDiscussionModal.less
Labels: type/bug, type/accessibility

#3420 fix(regression): PostStreamState loadCount static member
  framework/core/js/src/forum/states/PostStreamState.ts
Labels: type/regression

#3425 fix(typings): treat color preview settings component type as specific string, not generic
  framework/core/js/src/admin/components/AdminPage.tsx
Labels: type/bug
