Repository flarum/framework, pull requests merged in 2022-06, with the labels that each got.

#3451 feat(translator): add locale getter
  framework/core/js/src/common/Translator.tsx
Labels: type/feature

#3437 fix(ext typings): remove some accessibility modifiers from Component
  framework/core/js/src/common/Component.ts
  framework/core/js/src/forum/components/Search.tsx
Labels: type/bug

#3450 fix(a11y: DiscussionListItem): controls dropdown not visible when tabbed into
  framework/core/less/forum/DiscussionListItem.less
Labels: type/accessibility

#3496 chore: enable and set up prettier for `flarum/tags`
  .github/workflows/flarum-tags-frontend.yml
  extensions/tags/js/package.json
  extensions/tags/js/src/@types/shims.d.ts
  extensions/tags/js/src/admin/addTagChangePermission.js
  extensions/tags/js/src/admin/addTagPermission.js
  extensions/tags/js/src/admin/addTagsHomePageOption.js
  extensions/tags/js/src/admin/addTagsPermissionScope.tsx
  extensions/tags/js/src/admin/components/EditTagModal.tsx
  extensions/tags/js/src/admin/components/TagsPage.js
  extensions/tags/js/src/admin/index.ts
  extensions/tags/js/src/common/compat.js
  extensions/tags/js/src/common/helpers/tagIcon.js
  extensions/tags/js/src/common/helpers/tagLabel.js
  extensions/tags/js/src/common/helpers/tagsLabel.js
  extensions/tags/js/src/common/utils/sortTags.tsx
  extensions/tags/js/src/forum/addTagComposer.js
  extensions/tags/js/src/forum/addTagControl.js
  extensions/tags/js/src/forum/addTagFilter.tsx
  extensions/tags/js/src/forum/addTagLabels.js
  extensions/tags/js/src/forum/addTagList.js
  extensions/tags/js/src/forum/components/DiscussionTaggedPost.js
  extensions/tags/js/src/forum/components/TagDiscussionModal.tsx
  extensions/tags/js/src/forum/components/TagHero.js
  extensions/tags/js/src/forum/components/TagLinkButton.js
  extensions/tags/js/src/forum/components/TagsPage.js
  extensions/tags/js/src/forum/index.ts
  extensions/tags/js/src/forum/states/TagListState.ts
  extensions/tags/js/src/forum/utils/getSelectableTags.js
  yarn.lock
Labels: type/cleanup, type/infrastructure

#3494 feat: support custom reusable setting components for `buildSettingComponent`
  framework/core/js/src/admin/components/AdminPage.tsx
Labels: type/feature

#3455 feature: adds advanced link handling in core
  framework/core/src/Extend/Link.php
  framework/core/src/Formatter/Formatter.php
Labels: type/feature
