Repository flarum/framework, pull requests merged in 2023-11, with the labels that each got.

#3919 fix: color input changes while typing
  framework/core/js/src/common/components/ColorPreviewInput.tsx
Labels: type/bug, javascript

#3909 chore: handle deprecations from 1.x
  extensions/embed/less/forum.less
  extensions/flags/js/src/forum/addFlagsToPosts.js
  extensions/flags/src/Command/DeleteFlagsHandler.php
  extensions/flags/src/Event/FlagsWillBeDeleted.php
  extensions/mentions/js/src/forum/forum.js
  extensions/mentions/js/src/forum/utils/getMentionText.js
  extensions/nicknames/extend.php
  framework/core/js/src/admin/components/LoadingModal.tsx
  framework/core/js/src/common/Application.tsx
  framework/core/js/src/common/Model.ts
  framework/core/js/src/common/Store.ts
  framework/core/js/src/common/components/Button.tsx
  framework/core/js/src/common/components/Modal.tsx
  framework/core/js/src/common/utils/ItemList.ts
  framework/core/js/src/common/utils/evented.js
  framework/core/js/src/forum/components/Search.tsx
  framework/core/js/src/forum/components/WelcomeHero.tsx
  framework/core/less/common/Button.less
  framework/core/less/common/mixins/vendor-prefixes.less
  framework/core/migrations/2023_10_23_000000_drop_post_number_index_column_from_discussions_table.php
  framework/core/src/Admin/AdminServiceProvider.php
  framework/core/src/Database/Migration.php
  framework/core/src/Discussion/Discussion.php
  framework/core/src/Discussion/DiscussionRepository.php
  framework/core/src/Extend/Frontend.php
  framework/core/src/Extend/Model.php
  framework/core/src/Extend/Settings.php
  framework/core/src/Forum/ForumServiceProvider.php
  framework/core/src/Frontend/RecompileFrontendAssets.php
  framework/core/src/Http/RequestUtil.php
  framework/core/src/Settings/DefaultSettingsRepository.php
  framework/core/src/Settings/SettingsRepositoryInterface.php
  framework/core/src/helpers.php
  framework/core/tests/integration/extenders/SettingsTest.php
  framework/core/tests/integration/policy/DiscussionPolicyTest.php
Labels: type/cleanup, breaking-changes, javascript

#3918 fix: paginated list limit hard to change
  extensions/package-manager/js/src/admin/states/QueueState.ts
  framework/core/js/src/common/Store.ts
  framework/core/js/src/common/states/PaginatedListState.ts
  framework/core/js/src/forum/states/DiscussionListState.ts
  framework/core/js/src/forum/states/NotificationListState.ts
  framework/core/src/Api/Controller/AbstractListController.php
  framework/core/src/Api/Controller/ListDiscussionsController.php
  framework/core/src/Api/Controller/ListNotificationsController.php
  framework/core/src/Forum/Content/Index.php
Labels: javascript, type/extensibility

#3920 fix: handled API errors break preloaded content
  extensions/tags/src/Content/Tag.php
  extensions/tags/src/Content/Tags.php
  framework/core/src/Api/ApiServiceProvider.php
  framework/core/src/Api/Client.php
  framework/core/src/Api/ClientMiddlewarePipe.php
  framework/core/src/Forum/Content/Discussion.php
  framework/core/src/Forum/Content/Index.php
  framework/core/src/Forum/Content/User.php
  framework/core/src/Frontend/Frontend.php
Labels: type/bug

#3913 chore(mentions,emoji): tie autocomplete to editor instance
  extensions/emoji/js/src/forum/addComposerAutocomplete.js
  extensions/mentions/js/src/forum/addComposerAutocomplete.js
Labels: javascript, type/extensibility

#3922 chore: extract `FormModal` from `Modal`
  extensions/flags/js/src/forum/components/FlagPostModal.js
  extensions/nicknames/js/src/forum/components/NicknameModal.js
  extensions/statistics/js/src/admin/components/StatisticsWidgetDateSelectionModal.tsx
  extensions/suspend/js/src/forum/components/SuspendUserModal.js
  extensions/tags/js/src/admin/components/EditTagModal.tsx
  extensions/tags/js/src/common/components/TagSelectionModal.tsx
  extensions/tags/js/src/common/states/TagListState.ts
  framework/core/js/src/admin/components/CreateUserModal.tsx
  framework/core/js/src/admin/components/EditGroupModal.tsx
  framework/core/js/src/admin/components/LoadingModal.tsx
  framework/core/js/src/admin/components/SettingsModal.tsx
  framework/core/js/src/common/common.ts
  framework/core/js/src/common/components/EditUserModal.tsx
  framework/core/js/src/common/components/FormModal.tsx
  framework/core/js/src/common/components/Modal.tsx
  framework/core/js/src/forum/components/ChangeEmailModal.tsx
  framework/core/js/src/forum/components/ChangePasswordModal.tsx
  framework/core/js/src/forum/components/ForgotPasswordModal.tsx
  framework/core/js/src/forum/components/LogInModal.tsx
  framework/core/js/src/forum/components/NewAccessTokenModal.tsx
  framework/core/js/src/forum/components/RenameDiscussionModal.tsx
  framework/core/js/src/forum/components/SignUpModal.tsx
Labels: breaking-changes, javascript

#3923 feat: improve emoji autocomplete
  extensions/emoji/js/.prettierrc.json
  extensions/emoji/js/src/forum/addComposerAutocomplete.js
  extensions/emoji/less/forum.less
Labels: type/feature, javascript

#3931 perf(flags): add pagination to flags list
  extensions/flags/js/src/forum/components/FlagList.tsx
  extensions/flags/js/src/forum/components/FlagsDropdown.tsx
  extensions/flags/js/src/forum/states/FlagListState.tsx
  extensions/flags/src/Api/Controller/ListFlagsController.php
Labels: type/performance
