Repository flarum/framework, pull requests merged in 2023-01, with the labels that each got.

#3716 fix: load actor.groups on showforumcontroller
  framework/core/src/Api/Controller/ShowForumController.php
Labels: type/regression

#3666 feat(phpstan): foundation for usage in extensions
  composer.json
  framework/core/src/Database/AbstractModel.php
  framework/core/src/Extend/Model.php
  framework/core/tests/integration/extenders/ModelTest.php
  php-packages/phpstan/extension.neon
  php-packages/phpstan/src/Attributes/AttributeProperty.php
  php-packages/phpstan/src/Attributes/ModelCastAttributeExtension.php
  php-packages/phpstan/src/Attributes/ModelDateAttributesExtension.php
  php-packages/phpstan/src/Extender/Extender.php
  php-packages/phpstan/src/Extender/FilesProvider.php
  php-packages/phpstan/src/Extender/MethodCall.php
  php-packages/phpstan/src/Extender/Resolver.php
  php-packages/phpstan/src/Relations/ModelRelationsExtension.php
  php-packages/phpstan/src/Relations/RelationMethod.php
  php-packages/phpstan/src/Relations/RelationProperty.php
Labels: type/feature, type/extensibility

#3645 feat: introduce frontend extenders
  extensions/flags/js/src/forum/extend.ts
  extensions/flags/js/src/forum/index.ts
  extensions/likes/js/src/forum/addLikesTabToUserProfile.tsx
  extensions/likes/js/src/forum/extend.ts
  extensions/likes/js/src/forum/index.js
  extensions/likes/js/tsconfig.json
  extensions/lock/js/src/forum/extend.ts
  extensions/lock/js/src/forum/index.js
  extensions/lock/js/tsconfig.json
  extensions/mentions/js/src/forum/extend.ts
  extensions/mentions/js/src/forum/index.js
  extensions/mentions/js/tsconfig.json
  extensions/sticky/js/src/forum/extend.ts
  extensions/sticky/js/src/forum/index.js
  extensions/sticky/js/tsconfig.json
  extensions/subscriptions/js/src/forum/extend.ts
  extensions/subscriptions/js/src/forum/index.js
  extensions/tags/js/src/forum/extend.ts
  extensions/tags/js/src/forum/index.ts
  framework/core/js/src/common/Application.tsx
  framework/core/js/src/common/compat.ts
  framework/core/js/src/common/extend/Model.js
  framework/core/js/src/common/extend/PostTypes.js
  framework/core/js/src/common/extend/Routes.js
  framework/core/js/src/common/extend/index.js
  framework/core/js/src/common/extenders/IExtender.ts
  framework/core/js/src/common/extenders/PostTypes.ts
  framework/core/js/src/common/extenders/Routes.ts
  framework/core/js/src/common/extenders/index.ts
  framework/core/js/src/common/index.ts
Labels: type/feature, prio/high, javascript, needs-documentation

#3653 fix(tags): tag text color contrast
  extensions/tags/js/src/common/helpers/tagLabel.js
  extensions/tags/js/src/forum/addTagFilter.tsx
  extensions/tags/js/src/forum/addTagLabels.js
  extensions/tags/js/src/forum/components/TagHero.js
  extensions/tags/js/src/forum/components/TagsPage.js
  extensions/tags/less/common/TagLabel.less
  extensions/tags/less/forum.less
  extensions/tags/less/forum/TagHero.less
  extensions/tags/less/forum/TagTiles.less
  framework/core/js/src/common/compat.ts
  framework/core/js/src/common/helpers/textContrastClass.ts
  framework/core/js/src/common/utils/isDark.ts
  framework/core/less/common/root.less
  framework/core/less/common/scaffolding.less
  framework/core/less/common/variables.less
  framework/core/less/forum/Hero.less
Labels: type/accessibility

#3698 feat: expose {time} to eventPost data, fix renamed tooltip
  extensions/lock/locale/en.yml
  extensions/sticky/locale/en.yml
  extensions/tags/locale/en.yml
  framework/core/js/src/forum/components/DiscussionRenamedPost.js
  framework/core/js/src/forum/components/EventPost.js
  framework/core/locale/core.yml
Labels: type/feature

#3667 chore(phpstan): enable phpstan in bundled extensions
  extensions/akismet/extend.php
  extensions/akismet/src/Listener/ValidatePost.php
  extensions/approval/extend.php
  extensions/approval/src/Listener/UnapproveNewContent.php
  extensions/approval/src/Listener/UpdateDiscussionAfterPostApproval.php
  extensions/flags/extend.php
  extensions/flags/src/Api/Controller/ListFlagsController.php
  extensions/flags/src/Api/Serializer/FlagSerializer.php
  extensions/flags/src/Command/CreateFlagHandler.php
  extensions/flags/src/Command/DeleteFlagsHandler.php
  extensions/flags/src/Flag.php
  extensions/lock/extend.php
  extensions/lock/src/Access/DiscussionPolicy.php
  extensions/lock/src/Post/DiscussionLockedPost.php
  extensions/mentions/src/ConfigureMentions.php
  extensions/mentions/src/Formatter/FormatPostMentions.php
  extensions/mentions/src/Formatter/FormatUserMentions.php
  extensions/mentions/src/Listener/UpdateMentionsMetadataWhenVisible.php
  extensions/nicknames/extend.php
  extensions/nicknames/src/NicknameFullTextGambit.php
  extensions/package-manager/src/Api/Controller/ListTasksController.php
  extensions/package-manager/src/Command/AbstractActionCommand.php
  extensions/package-manager/src/Command/CheckForUpdates.php
  extensions/package-manager/src/Command/GlobalUpdate.php
  extensions/package-manager/src/Command/MajorUpdate.php
  extensions/package-manager/src/Command/MinorUpdate.php
  extensions/package-manager/src/Command/RemoveExtension.php
  extensions/package-manager/src/Command/RequireExtension.php
  extensions/package-manager/src/Command/UpdateExtension.php
  extensions/package-manager/src/Command/WhyNot.php
  extensions/package-manager/src/Composer/ComposerAdapter.php
  extensions/package-manager/src/Job/ComposerCommandJob.php
  extensions/package-manager/src/Job/Dispatcher.php
  extensions/package-manager/src/Settings/LastUpdateRun.php
  extensions/package-manager/src/Task/Task.php
  extensions/pusher/src/Api/Controller/AuthController.php
  extensions/pusher/src/Listener/PushNewPost.php
  extensions/pusher/src/Provider/PusherProvider.php
  extensions/sticky/extend.php
  extensions/sticky/src/PinStickiedDiscussionsToTop.php
  extensions/sticky/src/Post/DiscussionStickiedPost.php
  extensions/subscriptions/extend.php
  extensions/suspend/extend.php
  extensions/suspend/src/Listener/SaveSuspensionToDatabase.php
  extensions/tags/src/Access/DiscussionPolicy.php
  extensions/tags/src/Access/GlobalPolicy.php
  extensions/tags/src/Api/Serializer/TagSerializer.php
  extensions/tags/src/Listener/UpdateTagMetadata.php
  extensions/tags/src/Post/DiscussionTaggedPost.php
  extensions/tags/src/Query/TagFilterGambit.php
  extensions/tags/src/Tag.php
  extensions/tags/src/TagRepository.php
  extensions/tags/src/Utf8SlugDriver.php
  framework/core/src/Extend/Validator.php
  framework/core/src/Extension/Extension.php
  framework/core/src/Notification/Blueprint/BlueprintInterface.php
  framework/core/src/Notification/MailableInterface.php
  framework/core/src/Post/Event/Posted.php
  phpstan.neon
Labels: type/cleanup
