Repository flarum/framework, pull requests merged in 2023-09, with the labels that each got.

#3877 chore: normalize form semantics
  extensions/flags/js/src/forum/components/FlagPostModal.js
  extensions/likes/js/src/forum/components/PostLikesModal.tsx
  extensions/mentions/js/src/forum/components/MentionedByModal.tsx
  extensions/nicknames/js/src/forum/components/NicknameModal.js
  extensions/suspend/js/src/forum/components/SuspendUserModal.js
  extensions/suspend/js/src/forum/components/SuspensionInfoModal.js
  extensions/tags/js/src/admin/components/EditTagModal.tsx
  extensions/tags/js/src/admin/components/TagsPage.js
  extensions/tags/less/admin/EditTagModal.less
  framework/core/js/src/admin/components/AdminPage.tsx
  framework/core/js/src/admin/components/AppearancePage.tsx
  framework/core/js/src/admin/components/BasicsPage.tsx
  framework/core/js/src/admin/components/CreateUserModal.tsx
  framework/core/js/src/admin/components/EditGroupModal.tsx
  framework/core/js/src/admin/components/ExtensionPage.tsx
  framework/core/js/src/admin/components/HeaderSecondary.js
  framework/core/js/src/admin/components/MailPage.tsx
  framework/core/js/src/admin/components/SettingsModal.tsx
  framework/core/js/src/common/components/EditUserModal.tsx
  framework/core/js/src/common/components/FieldSet.js
  framework/core/js/src/common/components/FieldSet.tsx
  framework/core/js/src/common/components/Form.tsx
  framework/core/js/src/common/components/LinkButton.js
  framework/core/js/src/forum/components/ChangeEmailModal.tsx
  framework/core/js/src/forum/components/ChangePasswordModal.tsx
  framework/core/js/src/forum/components/ForgotPasswordModal.tsx
  framework/core/js/src/forum/components/NewAccessTokenModal.tsx
  framework/core/js/src/forum/components/RenameDiscussionModal.tsx
  framework/core/js/src/forum/components/SettingsPage.tsx
  framework/core/js/src/forum/components/UserSecurityPage.tsx
  framework/core/less/admin/AppearancePage.less
  framework/core/less/admin/BasicsPage.less
  framework/core/less/admin/EditGroupModal.less
  framework/core/less/admin/MailPage.less
  framework/core/less/common/Button.less
  framework/core/less/common/Form.less
  framework/core/less/common/FormControl.less
  framework/core/less/common/Modal.less
  framework/core/less/common/scaffolding.less
  framework/core/less/forum/SettingsPage.less
  framework/core/less/forum/UserSecurityPage.less
Labels: breaking-changes, javascript, type/theme(ing), type/extensibility

#3879 feat: extract reusable components from `NotificationsDropdown`
  extensions/flags/js/src/forum/components/FlagList.js
  extensions/flags/js/src/forum/components/FlagList.tsx
  extensions/flags/js/src/forum/components/FlagsDropdown.js
  extensions/flags/js/src/forum/components/FlagsDropdown.tsx
  extensions/flags/js/src/forum/states/FlagListState.js
  extensions/flags/js/src/forum/states/FlagListState.tsx
  extensions/flags/less/forum.less
  extensions/lock/js/src/forum/components/DiscussionLockedNotification.js
  extensions/subscriptions/js/src/forum/components/NewPostNotification.js
  extensions/suspend/js/src/forum/components/UserSuspendedNotification.js
  extensions/suspend/js/src/forum/components/UserUnsuspendedNotification.js
  framework/core/js/src/forum/components/HeaderDropdown.tsx
  framework/core/js/src/forum/components/HeaderList.tsx
  framework/core/js/src/forum/components/HeaderListGroup.tsx
  framework/core/js/src/forum/components/HeaderListItem.tsx
  framework/core/js/src/forum/components/Notification.tsx
  framework/core/js/src/forum/components/NotificationList.js
  framework/core/js/src/forum/components/NotificationsDropdown.tsx
  framework/core/less/forum.less
  framework/core/less/forum/HeaderDropdown.less
  framework/core/less/forum/HeaderList.less
Labels: breaking-changes, javascript, type/theme(ing), type/extensibility

#3882 feat: reusable `UploadImageButton` component
  framework/core/js/src/admin/components/AdminPage.tsx
  framework/core/js/src/admin/components/AppearancePage.tsx
  framework/core/js/src/admin/components/UploadImageButton.js
  framework/core/js/src/admin/components/UploadImageButton.tsx
Labels: javascript, type/extensibility, needs-documentation

#3883 feat: customizable default footer component
  framework/core/js/src/forum/ForumApplication.tsx
  framework/core/js/src/forum/components/Footer.tsx
  framework/core/views/frontend/forum.blade.php
Labels: type/theme(ing)

#3870 chore: Test using MySQL 8.1 also
  .github/workflows/REUSABLE_backend.yml
Labels: type/infrastructure

#3885 refactor: move gambits to frontend
  extensions/lock/js/src/admin/extend.ts
  extensions/lock/js/src/admin/index.js
  extensions/lock/js/src/common/extend.ts
  extensions/lock/js/src/common/query/discussions/LockedGambit.ts
  extensions/lock/js/src/forum/extend.ts
  extensions/sticky/js/src/admin/extend.ts
  extensions/sticky/js/src/admin/index.js
  extensions/sticky/js/src/common/extend.ts
  extensions/sticky/js/src/common/query/discussions/StickyGambit.ts
  extensions/sticky/js/src/forum/extend.ts
  extensions/subscriptions/extend.php
  extensions/subscriptions/js/admin.ts
  extensions/subscriptions/js/src/admin/extend.ts
  extensions/subscriptions/js/src/admin/index.ts
  extensions/subscriptions/js/src/common/extend.ts
  extensions/subscriptions/js/src/common/query/discussions/SubscriptionGambit.ts
  extensions/subscriptions/js/src/forum/extend.ts
  extensions/suspend/js/src/admin/extend.ts
  extensions/suspend/js/src/admin/index.js
  extensions/suspend/js/src/common/extend.ts
  extensions/suspend/js/src/common/query/users/SuspendedGambit.ts
  extensions/suspend/js/src/forum/extend.ts
  extensions/tags/js/src/common/extend.ts
  extensions/tags/js/src/common/query/discussions/TagGambit.ts
  framework/core/js/src/common/GambitManager.ts
  framework/core/js/src/common/Store.ts
  framework/core/js/src/common/extenders/Search.ts
  framework/core/js/src/common/extenders/index.ts
  framework/core/js/src/common/query/IGambit.ts
  framework/core/js/src/common/query/discussions/AuthorGambit.ts
  framework/core/js/src/common/query/discussions/CreatedGambit.ts
  framework/core/js/src/common/query/discussions/HiddenGambit.ts
  framework/core/js/src/common/query/discussions/UnreadGambit.ts
  framework/core/js/src/common/query/users/EmailGambit.ts
  framework/core/js/src/common/query/users/GroupGambit.ts
  framework/core/js/tests/unit/common/GambitManager.test.ts
  framework/core/src/Discussion/Filter/AuthorFilter.php
  framework/core/src/Discussion/Filter/CreatedFilter.php
  framework/core/src/Discussion/Filter/HiddenFilter.php
  framework/core/src/Discussion/Filter/UnreadFilter.php
  framework/core/src/Discussion/Query/CreatedFilterGambit.php
  framework/core/src/Filter/FilterServiceProvider.php
  framework/core/src/Search/SearchServiceProvider.php
  framework/core/src/User/Filter/EmailFilter.php
  framework/core/src/User/Filter/GroupFilter.php
Labels: type/feature, breaking-changes, javascript, needs-documentation

#3890 fix(1.x,suspend): suspended users can abuse avatar upload
  extensions/suspend/src/Access/UserPolicy.php
  extensions/suspend/tests/fixtures/avatar.png
  extensions/suspend/tests/integration/api/users/UploadAvatarTest.php
  framework/core/src/User/Access/UserPolicy.php
  framework/core/src/User/Command/UploadAvatarHandler.php
Labels: type/bug

#3888 fix:(1.x) missing compat exports
  framework/core/js/src/common/compat.ts
  framework/core/js/src/forum/compat.ts
Labels: type/bug, javascript, type/extensibility

#3872 feat: notification unsubscribe & email overhaul with HTML multipart
  extensions/mentions/locale/en.yml
  extensions/mentions/src/Notification/GroupMentionedBlueprint.php
  extensions/mentions/src/Notification/PostMentionedBlueprint.php
  extensions/mentions/src/Notification/UserMentionedBlueprint.php
  extensions/mentions/views/emails/html/groupMentioned.blade.php
  extensions/mentions/views/emails/html/postMentioned.blade.php
  extensions/mentions/views/emails/html/userMentioned.blade.php
  extensions/mentions/views/emails/plain/groupMentioned.blade.php
  extensions/mentions/views/emails/plain/postMentioned.blade.php
  extensions/mentions/views/emails/plain/userMentioned.blade.php
  extensions/subscriptions/locale/en.yml
  extensions/subscriptions/src/Notification/NewPostBlueprint.php
  extensions/subscriptions/views/emails/html/newPost.blade.php
  extensions/subscriptions/views/emails/plain/newPost.blade.php
  extensions/suspend/locale/en.yml
  extensions/suspend/src/Notification/UserSuspendedBlueprint.php
  extensions/suspend/src/Notification/UserUnsuspendedBlueprint.php
  extensions/suspend/tests/integration/api/users/SuspendUserTest.php
  extensions/suspend/views/emails/html/suspended.blade.php
  extensions/suspend/views/emails/html/unsuspended.blade.php
  extensions/suspend/views/emails/plain/suspended.blade.php
  extensions/suspend/views/emails/plain/unsuspended.blade.php
  extensions/suspend/views/emails/suspended.blade.php
  extensions/suspend/views/emails/unsuspended.blade.php
  framework/core/js/src/admin/components/MailPage.tsx
  framework/core/locale/core.yml
  framework/core/migrations/2023_08_19_000000_create_unsubscribe_tokens_table.php
  framework/core/src/Api/Controller/SendTestMailController.php
  framework/core/src/Formatter/Formatter.php
  framework/core/src/Forum/Controller/UnsubscribeActionController.php
  framework/core/src/Forum/Controller/UnsubscribeViewController.php
  framework/core/src/Forum/ForumServiceProvider.php
  framework/core/src/Forum/routes.php
  framework/core/src/Install/Steps/WriteSettings.php
  framework/core/src/Mail/Job/SendInformationalEmailJob.php
  framework/core/src/Mail/Job/SendRawEmailJob.php
  framework/core/src/Mail/MailServiceProvider.php
  framework/core/src/Mail/Mailer.php
  framework/core/src/Notification/Job/SendEmailNotificationJob.php
  framework/core/src/Notification/MailableInterface.php
  framework/core/src/Notification/NotificationMailer.php
  framework/core/src/Notification/UnsubscribeToken.php
  framework/core/src/Queue/QueueFactory.php
  framework/core/src/Settings/SettingsServiceProvider.php
  framework/core/src/User/AccountActivationMailerTrait.php
  framework/core/src/User/EmailConfirmationMailer.php
  framework/core/src/User/Job/RequestPasswordResetJob.php
  framework/core/src/User/User.php
  framework/core/views/email/html/base.blade.php
  framework/core/views/email/html/information/base.blade.php
  framework/core/views/email/html/notification/base.blade.php
  framework/core/views/email/plain/base.blade.php
  framework/core/views/email/plain/information/base.blade.php
  framework/core/views/email/plain/notification/base.blade.php
  framework/core/views/unsubscribe-confirmation.blade.php
  framework/core/views/unsubscribe-error.blade.php
Labels: type/feature, breaking-changes, prio/high, extension-breaking, needs-documentation
