Repository flarum/framework, pull requests merged in 2023-04, with the labels that each got.

#3786 fix(tags): tag discussion modal filters with exact matches only after first index
  extensions/tags/js/src/common/components/TagSelectionModal.tsx
Labels: type/bug

#3785 fix: circular dependencies disable all involved extensions
  framework/core/locale/core.yml
  framework/core/src/Extension/Exception/CircularDependenciesException.php
  framework/core/src/Extension/Exception/CircularDependenciesExceptionHandler.php
  framework/core/src/Extension/ExtensionManager.php
  framework/core/src/Foundation/ErrorServiceProvider.php
Labels: type/bug

#3729 chore: extensibility improvements
  extensions/tags/js/src/common/helpers/tagLabel.js
  extensions/tags/js/src/forum/components/TagsPage.js
  framework/core/js/src/forum/components/ChangeEmailModal.tsx
  framework/core/js/src/forum/components/ChangePasswordModal.tsx
  framework/core/js/src/forum/components/DiscussionListItem.tsx
Labels: javascript, type/extensibility

#3788 fix: notification subject discussion eager loading fails
  framework/core/src/Api/Controller/ListNotificationsController.php
Labels: type/performance

#3784 feat(permission): add delete own posts permission
  framework/core/js/src/admin/components/PermissionGrid.tsx
  framework/core/locale/core.yml
  framework/core/src/Install/Steps/WriteSettings.php
  framework/core/src/Post/Access/PostPolicy.php
  framework/core/tests/integration/policy/PostPolicyTest.php
Labels: type/feature

#3733 Fix bug when infinite scroll was not initialised for notifications dropdown on big screens
  framework/core/js/src/forum/states/NotificationListState.ts
  framework/core/less/forum/NotificationsDropdown.less
  framework/core/src/Api/Controller/ListNotificationsController.php
Labels: type/bug

#3780 perf(core,mentions): limit `mentionedBy` post relation results
  composer.json
  extensions/mentions/extend.php
  extensions/mentions/js/src/@types/shims.d.ts
  extensions/mentions/js/src/forum/addMentionedByList.js
  extensions/mentions/js/src/forum/components/MentionedByModal.tsx
  extensions/mentions/js/src/forum/extend.ts
  extensions/mentions/js/src/forum/state/MentionedByModalState.ts
  extensions/mentions/locale/en.yml
  extensions/mentions/src/Api/LoadMentionedByRelationship.php
  extensions/mentions/src/Filter/MentionedPostFilter.php
  extensions/mentions/src/FilterVisiblePosts.php
  extensions/mentions/tests/integration/api/GroupMentionsTest.php
  extensions/mentions/tests/integration/api/ListPostsTest.php
  framework/core/composer.json
  framework/core/less/common/Dropdown.less
  framework/core/less/forum/Post.less
  framework/core/src/Api/Controller/ShowDiscussionController.php
  framework/core/src/Api/Controller/ShowPostController.php
  framework/core/src/Database/AbstractModel.php
  framework/core/src/Database/Eloquent/Collection.php
  framework/core/src/Extend/ApiController.php
  framework/core/src/Post/Post.php
Labels: prio/high, type/performance

#3799 fix: deleting a discussion from the profile does not visually remove it
  framework/core/js/src/common/compat.ts
  framework/core/js/src/common/utils/EventEmitter.ts
  framework/core/js/src/forum/states/DiscussionListState.ts
Labels: type/bug, javascript

#3769 feat(mentions,tags): tag mentions
  extensions/mentions/composer.json
  extensions/mentions/extend.php
  extensions/mentions/js/src/@types/shims.d.ts
  extensions/mentions/js/src/forum/addComposerAutocomplete.js
  extensions/mentions/js/src/forum/addPostMentionPreviews.js
  extensions/mentions/js/src/forum/compat.js
  extensions/mentions/js/src/forum/components/MentionsDropdownItem.tsx
  extensions/mentions/js/src/forum/extenders/Mentionables.ts
  extensions/mentions/js/src/forum/index.js
  extensions/mentions/js/src/forum/mentionables/GroupMention.tsx
  extensions/mentions/js/src/forum/mentionables/MentionableModel.ts
  extensions/mentions/js/src/forum/mentionables/MentionableModels.tsx
  extensions/mentions/js/src/forum/mentionables/PostMention.tsx
  extensions/mentions/js/src/forum/mentionables/TagMention.tsx
  extensions/mentions/js/src/forum/mentionables/UserMention.tsx
  extensions/mentions/js/src/forum/mentionables/formats/AtMentionFormat.ts
  extensions/mentions/js/src/forum/mentionables/formats/HashMentionFormat.ts
  extensions/mentions/js/src/forum/mentionables/formats/MentionFormat.ts
  extensions/mentions/js/src/forum/mentionables/formats/MentionFormats.ts
  extensions/mentions/js/src/forum/utils/getMentionText.js
  extensions/mentions/js/src/forum/utils/reply.js
  extensions/mentions/js/src/forum/utils/textFormatter.js
  extensions/mentions/js/tsconfig.json
  extensions/mentions/less/forum.less
  extensions/mentions/src/ConfigureMentions.php
  extensions/mentions/src/FilterVisiblePosts.php
  extensions/mentions/src/Formatter/CheckPermissions.php
  extensions/mentions/src/Formatter/FormatGroupMentions.php
  extensions/mentions/src/Formatter/FormatTagMentions.php
  extensions/mentions/src/Formatter/UnparseTagMentions.php
  extensions/mentions/src/Listener/UpdateMentionsMetadataWhenInvisible.php
  extensions/mentions/src/Listener/UpdateMentionsMetadataWhenVisible.php
  extensions/mentions/tests/integration/api/GroupMentionsTest.php
  extensions/mentions/tests/integration/api/TagMentionsTest.php
  extensions/tags/extend.php
  extensions/tags/less/common/TagLabel.less
  extensions/tags/migrations/2023_03_01_000000_create_post_mentions_tag_table.php
  extensions/tags/src/Api/Controller/ListTagsController.php
  extensions/tags/src/Search/Gambit/FulltextGambit.php
  extensions/tags/src/Search/TagSearcher.php
  extensions/tags/src/TagRepository.php
  extensions/tags/tests/integration/api/tags/ListWithFulltextSearchTest.php
  framework/core/js/dist-typings/common/extenders/IExtender.d.ts
  framework/core/js/src/common/extenders/IExtender.ts
  framework/core/src/Group/GroupRepository.php
  php-packages/phpstan/src/Extender/Resolver.php
Labels: type/feature, prio/high

#3804 fix(tags): not all tags are loaded in the permission grid
  extensions/tags/js/src/admin/addTagsPermissionScope.tsx
  extensions/tags/js/src/common/states/TagListState.ts
Labels: type/bug, javascript

#3802 chore[tags]: Change some methods from private to protected, to be able to extend the affected classes
  extensions/tags/src/Content/Tag.php
  extensions/tags/src/Content/Tags.php
Labels: type/extensibility

#3774 fix: `isDark()` utility can receive null value
  framework/core/js/src/common/helpers/textContrastClass.ts
  framework/core/js/src/common/utils/isDark.ts
Labels: type/bug, type/cleanup, javascript

#3809 fix(bbcode): localize quote `wrote` string
  extensions/bbcode/extend.php
  extensions/bbcode/locale/en.yml
Labels: type/extensibility

#3808 perf: speed up post creation time
  extensions/mentions/extend.php
  extensions/mentions/src/ConfigureMentions.php
  extensions/mentions/src/Formatter/EagerLoadMentionedModels.php
  extensions/mentions/src/Job/SendMentionsNotificationsJob.php
  extensions/mentions/src/Listener/UpdateMentionsMetadataWhenVisible.php
  framework/core/src/Formatter/Formatter.php
  framework/core/src/Notification/NotificationSyncer.php
  framework/core/tests/integration/notification/NotificationSyncerTest.php
Labels: type/performance
