Repository flarum/framework, pull requests merged in 2023-02, with the labels that each got.

#3646 feat: frontend `Model` extender
  .editorconfig
  extensions/flags/js/src/forum/extend.ts
  extensions/flags/js/src/forum/index.ts
  extensions/likes/js/src/forum/extend.ts
  extensions/likes/js/src/forum/index.js
  extensions/lock/js/src/forum/extend.ts
  extensions/lock/js/src/forum/index.js
  extensions/mentions/js/src/forum/addMentionedByList.js
  extensions/mentions/js/src/forum/extend.ts
  extensions/mentions/js/src/forum/index.js
  extensions/nicknames/js/src/forum/extend.ts
  extensions/nicknames/js/src/forum/index.js
  extensions/nicknames/js/tsconfig.json
  extensions/sticky/js/src/forum/extend.ts
  extensions/sticky/js/src/forum/index.js
  extensions/subscriptions/js/src/forum/extend.ts
  extensions/subscriptions/js/src/forum/index.js
  extensions/suspend/js/src/forum/extend.ts
  extensions/suspend/js/src/forum/index.js
  extensions/suspend/js/tsconfig.json
  extensions/tags/js/src/admin/index.ts
  extensions/tags/js/src/common/extend.ts
  extensions/tags/js/src/forum/extend.ts
  extensions/tags/js/src/forum/index.ts
  framework/core/js/src/common/Store.ts
  framework/core/js/src/common/extenders/Model.ts
  framework/core/js/src/common/extenders/Store.ts
  framework/core/js/src/common/extenders/index.ts
Labels: type/feature, prio/high, javascript, needs-documentation

#3678 feat(jest): create jest config package for unit testing
  framework/core/js/jest.config.cjs
  framework/core/js/package.json
  framework/core/js/src/common/utils/BasicEditorDriver.ts
  framework/core/js/src/forum/states/ComposerState.js
  framework/core/js/tests/unit/common/utils/abbreviateNumber.test.ts
  framework/core/js/tsconfig.json
  framework/core/js/webpack.config.cjs
  js-packages/jest-config/.gitignore
  js-packages/jest-config/LICENSE
  js-packages/jest-config/README.md
  js-packages/jest-config/index.cjs
  js-packages/jest-config/package.json
  js-packages/jest-config/setup-env.js
  js-packages/webpack-config/babel.config.js
  js-packages/webpack-config/index.js
  yarn.lock
Labels: type/feature, type/infrastructure, prio/high, needs-documentation

#3679 feat(jest): mithril component testing
  framework/core/js/tests/integration/common/components/Alert.test.ts
  framework/core/js/tsconfig.test.json
  js-packages/jest-config/README.md
  js-packages/jest-config/package.json
  js-packages/jest-config/setup-env.js
  js-packages/jest-config/shims.d.ts
  js-packages/jest-config/test-matchers.ts
  js-packages/jest-config/tsconfig.json
  yarn.lock
Labels: type/feature, type/infrastructure, prio/high, needs-documentation

#3730 feat(actions): allow running JS tests in GH actions
  .github/workflows/REUSABLE_frontend.yml
  .github/workflows/frontend.yml
Labels: type/feature, type/infrastructure, javascript, needs-documentation

#3724 feat(seo): shift h1 tag from logo to discussion title
  extensions/package-manager/js/src/admin/components/ControlSection.tsx
  extensions/package-manager/js/src/admin/components/QueueSection.tsx
  extensions/tags/js/src/forum/components/TagHero.js
  extensions/tags/views/frontend/content/tag.blade.php
  extensions/tags/views/frontend/content/tags.blade.php
  framework/core/js/src/admin/components/AdminHeader.js
  framework/core/js/src/admin/components/ExtensionPage.tsx
  framework/core/js/src/forum/components/DiscussionHero.js
  framework/core/js/src/forum/components/UserCard.js
  framework/core/js/src/forum/components/WelcomeHero.tsx
  framework/core/less/forum/Hero.less
  framework/core/views/frontend/admin.blade.php
  framework/core/views/frontend/forum.blade.php
Labels: javascript, type/seo

#3709 chore: php 8.2
  .github/workflows/REUSABLE_backend.yml
  .github/workflows/flarum-package-manager-backend.yml
  composer.json
  extensions/mentions/migrations/2022_05_20_000005_add_created_at_to_post_mentions_post_table.php
  extensions/mentions/migrations/2022_05_20_000006_add_created_at_to_post_mentions_user_table.php
  extensions/package-manager/src/Command/AbstractActionCommand.php
  extensions/tags/migrations/2022_05_20_000003_add_timestamps_to_tags_table.php
  extensions/tags/migrations/2022_05_20_000004_add_created_at_to_discussion_tag_table.php
  extensions/tags/src/Access/ScopeDiscussionVisibilityForAbility.php
  framework/core/composer.json
  framework/core/src/Api/Controller/ListNotificationsController.php
  framework/core/src/Discussion/Event/UserRead.php
  framework/core/tests/unit/Foundation/ExtensionDependencyResolutionTest.php
Labels: prio/high

#3731 feat(seo): Use h2 header for discussions on discussions list
  framework/core/js/src/forum/components/DiscussionListItem.tsx
  framework/core/js/src/forum/components/DiscussionListPane.js
  framework/core/views/frontend/content/discussion.blade.php
  framework/core/views/frontend/content/index.blade.php
Labels: javascript, type/seo

#3732 feat(seo): Do not use h3 header for poster author in posts stream
  framework/core/js/src/forum/components/PostUser.js
  framework/core/js/src/forum/components/ReplyPlaceholder.js
  framework/core/less/forum/Post.less
  framework/core/views/frontend/content/discussion.blade.php
Labels: javascript, type/seo

#3741 feat: improved page navigation for users list
  framework/core/js/src/admin/components/UserListPage.tsx
  framework/core/less/admin/UsersListPage.less
  framework/core/locale/core.yml
Labels: type/feature, prio/low

#3740 feat: add display name column to admin users list
  framework/core/js/src/admin/components/UserListPage.tsx
  framework/core/locale/core.yml
Labels: type/feature, prio/low

#3737 fix(tags): clickable tag labels have underline
  extensions/tags/less/common/TagLabel.less
Labels: type/theme(ing)

#3587 feat: access tokens user management UI
  composer.json
  framework/core/composer.json
  framework/core/js/package.json
  framework/core/js/src/admin/components/PermissionGrid.tsx
  framework/core/js/src/common/Application.tsx
  framework/core/js/src/common/components/LabelValue.tsx
  framework/core/js/src/common/models/AccessToken.ts
  framework/core/js/src/common/utils/string.ts
  framework/core/js/src/forum/components/AccessTokensList.tsx
  framework/core/js/src/forum/components/NewAccessTokenModal.tsx
  framework/core/js/src/forum/components/UserPage.tsx
  framework/core/js/src/forum/components/UserSecurityPage.tsx
  framework/core/js/src/forum/routes.ts
  framework/core/js/src/forum/states/UserSecurityPageState.ts
  framework/core/less/common/Button.less
  framework/core/less/common/LabelValue.less
  framework/core/less/common/common.less
  framework/core/less/forum.less
  framework/core/less/forum/UserSecurityPage.less
  framework/core/locale/core.yml
  framework/core/migrations/2022_08_06_000000_change_access_tokens_last_activity_at_to_nullable.php
  framework/core/src/Api/Controller/CreateAccessTokenController.php
  framework/core/src/Api/Controller/CreateTokenController.php
  framework/core/src/Api/Controller/DeleteAccessTokenController.php
  framework/core/src/Api/Controller/ListAccessTokensController.php
  framework/core/src/Api/Controller/TerminateAllOtherSessionsController.php
  framework/core/src/Api/Serializer/AccessTokenSerializer.php
  framework/core/src/Api/Serializer/ForumSerializer.php
  framework/core/src/Api/routes.php
  framework/core/src/Filter/FilterServiceProvider.php
  framework/core/src/Http/Access/AccessTokenPolicy.php
  framework/core/src/Http/Access/ScopeAccessTokenVisibility.php
  framework/core/src/Http/AccessToken.php
  framework/core/src/Http/Event/DeveloperTokenCreated.php
  framework/core/src/Http/Filter/AccessTokenFilterer.php
  framework/core/src/Http/Filter/UserFilter.php
  framework/core/src/Http/HttpServiceProvider.php
  framework/core/src/Http/RememberAccessToken.php
  framework/core/src/Http/SessionAccessToken.php
  framework/core/src/User/UserServiceProvider.php
  framework/core/tests/integration/api/access_tokens/CreateTest.php
  framework/core/tests/integration/api/access_tokens/DeleteTest.php
  framework/core/tests/integration/api/access_tokens/ListTest.php
  php-packages/testing/src/integration/BuildsHttpRequests.php
  yarn.lock
Labels: type/feature, prio/high

#3605 feat: global logout to clear all sessions, access tokens, email tokens and password tokens
  framework/core/js/src/forum/components/UserSecurityPage.tsx
  framework/core/js/src/forum/states/UserSecurityPageState.ts
  framework/core/locale/core.yml
  framework/core/src/Forum/Controller/GlobalLogOutController.php
  framework/core/src/Forum/Controller/LogOutController.php
  framework/core/src/Forum/routes.php
  framework/core/src/User/Event/LoggedOut.php
  framework/core/tests/integration/forum/GlobalLogoutTest.php
Labels: type/feature

#3738 fix(mentions): post reply mention missing notification on approval
  extensions/mentions/extend.php
  extensions/mentions/src/Listener/UpdateMentionsMetadataWhenVisible.php
Labels: type/bug

#3571 fix: normal logout affects all sessions
  framework/core/src/Forum/Controller/LogOutController.php
Labels: type/bug
