Repository flarum/framework, pull requests merged in 2023-10, with the labels that each got.

#3898 [1.x] Conditional extender instantiation
  framework/core/src/Extend/Conditional.php
  framework/core/tests/integration/extenders/ConditionalTest.php
Labels: prio/high, type/extensibility

#3900 [1.x] Console extender does not accept `::class` attribute for Schedule
  framework/core/src/Extend/Console.php
  framework/core/tests/integration/extenders/ConsoleTest.php
Labels: type/extensibility

#3903 fix: console extender does not accept `::class` attribute for schedule
  framework/core/src/Extend/Console.php
  framework/core/tests/integration/extenders/ConsoleTest.php
Labels: type/extensibility

#3904 chore: remove ExtenderInterface[] as a conditional option, only support callable or ::class invoke
  extensions/mentions/extend.php
  framework/core/src/Extend/Conditional.php
  framework/core/tests/integration/extenders/ConditionalTest.php
Labels: type/extensibility

#3905 feat: advanced page and localized driver settings
  extensions/nicknames/js/src/admin/index.js
  extensions/nicknames/locale/en.yml
  extensions/tags/js/src/admin/components/TagsPage.js
  extensions/tags/less/admin/TagsPage.less
  framework/core/js/src/admin/AdminApplication.tsx
  framework/core/js/src/admin/components/AdminNav.js
  framework/core/js/src/admin/components/AdminPage.tsx
  framework/core/js/src/admin/components/AdvancedPage.tsx
  framework/core/js/src/admin/components/BasicsPage.tsx
  framework/core/js/src/admin/components/FormSectionGroup.tsx
  framework/core/js/src/admin/components/StatusWidget.js
  framework/core/js/src/admin/routes.ts
  framework/core/less/admin.less
  framework/core/less/admin/FormSectionGroup.less
  framework/core/locale/core.yml
  framework/core/src/Admin/Content/AdminPayload.php
  framework/core/src/Install/Steps/WriteSettings.php
  framework/core/src/Settings/SettingsServiceProvider.php
Labels: type/feature, javascript, type/extensibility

#3906 feat: allow getting total search results and replacing filters
  framework/core/src/Extend/SearchDriver.php
  framework/core/src/Search/Database/AbstractSearcher.php
  framework/core/src/Search/SearchResults.php
  framework/core/tests/integration/extenders/SearchDriverTest.php
Labels: type/feature, type/extensibility

#3911 fix(webpack-config): split chunks can fail in dev mode
  js-packages/webpack-config/src/index.cjs
Labels: type/bug, javascript, webpack-config

#3765 feat: frontend content flexible order priorities
  framework/core/src/Admin/AdminServiceProvider.php
  framework/core/src/Extend/Frontend.php
  framework/core/src/Forum/ForumServiceProvider.php
  framework/core/src/Frontend/Frontend.php
  framework/core/src/Frontend/FrontendServiceProvider.php
  framework/core/src/Http/RouteHandlerFactory.php
  framework/core/tests/integration/extenders/FrontendContentTest.php
Labels: breaking-changes, type/extensibility, needs-documentation

#3910 chore: use `::class` syntax to fetch class name instead of `get_class()` function
  extensions/flags/src/Api/Serializer/FlagSerializer.php
  extensions/package-manager/src/Api/Serializer/TaskSerializer.php
  extensions/tags/src/Api/Serializer/TagSerializer.php
  framework/core/src/Api/Serializer/AccessTokenSerializer.php
  framework/core/src/Api/Serializer/BasicDiscussionSerializer.php
  framework/core/src/Api/Serializer/BasicPostSerializer.php
  framework/core/src/Api/Serializer/BasicUserSerializer.php
  framework/core/src/Api/Serializer/CurrentUserSerializer.php
  framework/core/src/Api/Serializer/GroupSerializer.php
  framework/core/src/Api/Serializer/NotificationSerializer.php
  framework/core/src/Bus/Dispatcher.php
  framework/core/src/Extension/Exception/ExtensionBootError.php
  framework/core/src/Foundation/Application.php
  framework/core/src/Foundation/ApplicationInfoProvider.php
  framework/core/src/Foundation/Concerns/InteractsWithLaravel.php
  framework/core/src/Foundation/ErrorHandling/Registry.php
  framework/core/src/Frontend/Compiler/Source/SourceCollector.php
  framework/core/src/Http/Server.php
  framework/core/src/Notification/Notification.php
  framework/core/src/Search/GambitManager.php
  framework/core/src/User/Access/Gate.php
  framework/core/tests/integration/extenders/FilesystemTest.php
  framework/core/tests/integration/extenders/SessionTest.php
  php-packages/phpstan/src/Extender/Extender.php
  php-packages/phpstan/src/Extender/Resolver.php
Labels: type/cleanup

#3912 chore: avoid using `.fa()` mixins and `@fa-var` vars
  extensions/mentions/less/forum.less
  extensions/mentions/src/ConfigureMentions.php
  extensions/tags/js/src/common/components/TagSelectionModal.tsx
  extensions/tags/less/common/TagSelectionModal.less
  framework/core/js/src/forum/components/Composer.js
  framework/core/js/src/forum/components/Search.tsx
  framework/core/less/common/Search.less
  framework/core/less/common/Select.less
  framework/core/less/common/Table.less
  framework/core/less/forum/Composer.less
Labels: type/cleanup
