Repository flarum/framework, pull requests merged in 2023-03, with the labels that each got.

#3753 chore: hide developer tokens section in if there is nothing to display or create
  framework/core/js/src/forum/components/UserSecurityPage.tsx
Labels: type/cleanup

#3759 feat: conditional extenders
  framework/core/src/Extend/Conditional.php
  framework/core/src/Extension/Extension.php
  framework/core/src/User/Access/Gate.php
  framework/core/tests/integration/extenders/ConditionalTest.php
  framework/core/tests/integration/extenders/LocalesTest.php
Labels: type/feature, needs-documentation

#3772 Fix: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
  extensions/mentions/src/Listener/UpdateMentionsMetadataWhenVisible.php
Labels: type/extensibility

#3773 fix: empty string displayed as SelectDropdown title
  framework/core/js/src/common/components/SelectDropdown.tsx
Labels: type/bug, prio/high, javascript
