Repository flarum/framework, pull requests merged in 2023-06, with the labels that each got.

#3699 perf: transpile js to es6
  js-packages/webpack-config/.yarn/releases/yarn-3.1.0.cjs
  js-packages/webpack-config/.yarnrc.yml
  js-packages/webpack-config/babel.config.js
  js-packages/webpack-config/index.js
  js-packages/webpack-config/package.json
Labels: type/cleanup, type/infrastructure, breaking-changes, extension-breaking, javascript, type/performance

#3835 chore(phpstan): upgrade to be compatible with latest dependency updates
  .github/workflows/REUSABLE_backend.yml
  composer.json
  extensions/mentions/src/ConfigureMentions.php
  extensions/package-manager/src/Composer/ComposerAdapter.php
  extensions/pusher/composer.json
  extensions/pusher/src/Api/Controller/AuthController.php
  extensions/pusher/src/Listener/PushNewPost.php
  extensions/pusher/src/Provider/PusherProvider.php
  extensions/pusher/src/SendPusherNotificationsJob.php
  extensions/tags/src/Listener/UpdateTagMetadata.php
  extensions/tags/src/Tag.php
  extensions/tags/src/TagRepository.php
  framework/core/src/Api/ApiKey.php
  framework/core/src/Api/Controller/ShowDiscussionController.php
  framework/core/src/Api/Controller/TerminateAllOtherSessionsController.php
  framework/core/src/Api/Controller/UpdateDiscussionController.php
  framework/core/src/Api/Serializer/AbstractSerializer.php
  framework/core/src/Console/Schedule.php
  framework/core/src/Database/Eloquent/Collection.php
  framework/core/src/Discussion/Discussion.php
  framework/core/src/Discussion/DiscussionRepository.php
  framework/core/src/Discussion/UserState.php
  framework/core/src/Extension/ExtensionManager.php
  framework/core/src/Foundation/Application.php
  framework/core/src/Foundation/Container.php
  framework/core/src/Foundation/InstalledSite.php
  framework/core/src/Group/Group.php
  framework/core/src/Group/Permission.php
  framework/core/src/Http/AccessToken.php
  framework/core/src/Install/Steps/EnableBundledExtensions.php
  framework/core/src/Locale/TranslatorInterface.php
  framework/core/src/Notification/Notification.php
  framework/core/src/Notification/NotificationRepository.php
  framework/core/src/Notification/NotificationSyncer.php
  framework/core/src/Post/Post.php
  framework/core/src/User/EmailToken.php
  framework/core/src/User/PasswordToken.php
  framework/core/src/User/User.php
  php-packages/phpstan/bootstrap.php
  php-packages/phpstan/composer.json
  php-packages/phpstan/larastan-extension.neon
  php-packages/phpstan/phpstan-baseline.neon
  php-packages/phpstan/src/Relations/RelationProperty.php
  php-packages/testing/src/integration/Setup/Bootstrapper.php
  php-packages/testing/src/integration/TestCase.php
Labels: type/infrastructure, dependencies, breaking-changes

#3831 chore: upgrade to mithril 2.2
  extensions/mentions/js/src/forum/mentionables/PostMention.tsx
  extensions/mentions/js/src/forum/mentionables/UserMention.tsx
  framework/core/js/package.json
  framework/core/js/src/common/components/Link.js
  framework/core/js/src/common/helpers/username.tsx
  framework/core/js/src/common/utils/extractText.ts
  framework/core/js/src/forum/components/UsersSearchSource.tsx
  yarn.lock
Labels: dependencies, breaking-changes, extension-breaking, javascript

#3813 Do not catch exceptions when testing Console commands
  framework/core/tests/integration/extenders/ConsoleTest.php
  php-packages/testing/src/integration/ConsoleTestCase.php
Labels: type/infrastructure

#3837 chore: upgrade Wikimedia/less.php to 4.1
  composer.json
  framework/core/composer.json
Labels: type/infrastructure, dependencies
