Repository flarum/framework, pull requests merged in 2023-07, with the labels that each got.

#3832 fix(mentions): missed post mentions UI changes
  extensions/mentions/js/src/forum/addMentionedByList.js
  extensions/mentions/src/Api/LoadMentionedByRelationship.php
Labels: type/bug, type/regression

#3855 fix(regression): Webpack not working on Windows with new export registry
  js-packages/webpack-config/src/autoExportLoader.cjs
Labels: type/regression

#3848 feat: make WelcomeHero extensible
  framework/core/js/src/forum/components/WelcomeHero.tsx
Labels: type/extensibility
