Repository flarum/framework, pull requests merged in 2023-05, with the labels that each got.

#3816 feat: cli command for enabling or disabling an extension
  framework/core/src/Console/ConsoleServiceProvider.php
  framework/core/src/Extension/Console/ToggleExtensionCommand.php
Labels: type/feature, type/infrastructure, needs-documentation

#3795 fix: filter values are not validated
  extensions/likes/src/Query/LikedByFilter.php
  extensions/lock/src/Query/LockedFilterGambit.php
  extensions/mentions/src/Filter/MentionedFilter.php
  extensions/sticky/src/Query/StickyFilterGambit.php
  extensions/subscriptions/src/Query/SubscriptionFilterGambit.php
  extensions/suspend/src/Query/SuspendedFilterGambit.php
  extensions/tags/src/Filter/PostTagFilter.php
  extensions/tags/src/Query/TagFilterGambit.php
  framework/core/locale/core.yml
  framework/core/src/Api/Controller/ListPostsController.php
  framework/core/src/Discussion/Query/AuthorFilterGambit.php
  framework/core/src/Discussion/Query/CreatedFilterGambit.php
  framework/core/src/Discussion/Query/HiddenFilterGambit.php
  framework/core/src/Discussion/Query/UnreadFilterGambit.php
  framework/core/src/Filter/FilterInterface.php
  framework/core/src/Filter/ValidateFilterTrait.php
  framework/core/src/Group/Filter/HiddenFilter.php
  framework/core/src/Http/Filter/UserFilter.php
  framework/core/src/Post/Filter/AuthorFilter.php
  framework/core/src/Post/Filter/DiscussionFilter.php
  framework/core/src/Post/Filter/IdFilter.php
  framework/core/src/Post/Filter/NumberFilter.php
  framework/core/src/Post/Filter/TypeFilter.php
  framework/core/src/Post/PostRepository.php
  framework/core/src/User/Query/EmailFilterGambit.php
  framework/core/src/User/Query/GroupFilterGambit.php
  framework/core/src/User/UserRepository.php
Labels: type/infrastructure

#3744 feat: add user creation to users list page
  framework/core/js/src/admin/compat.ts
  framework/core/js/src/admin/components/CreateUserModal.tsx
  framework/core/js/src/admin/components/UserListPage.tsx
  framework/core/js/src/common/utils/string.ts
  framework/core/less/admin.less
  framework/core/less/admin/CreateUserModal.less
  framework/core/less/admin/UsersListPage.less
  framework/core/locale/core.yml
Labels: type/feature
