Repository flarum/framework, pull requests merged in 2024-09, with the labels that each got.

#4019 feat: post search adapted with global search
  extensions/likes/js/src/common/extend.ts
  extensions/likes/js/src/common/query/posts/LikedByGambit.ts
  extensions/likes/js/src/forum/components/LikesUserPage.ts
  extensions/likes/js/src/forum/components/LikesUserPage.tsx
  extensions/likes/js/src/forum/extend.ts
  extensions/likes/js/src/forum/index.js
  extensions/likes/locale/en.yml
  extensions/likes/src/Query/LikedByFilter.php
  extensions/likes/src/Query/LikedFilter.php
  extensions/mentions/js/src/admin/extend.ts
  extensions/mentions/js/src/admin/index.js
  extensions/mentions/js/src/common/extend.ts
  extensions/mentions/js/src/common/query/posts/MentionedGambit.ts
  extensions/mentions/js/src/forum/components/MentionsUserPage.js
  extensions/mentions/js/src/forum/components/MentionsUserPage.ts
  extensions/mentions/js/src/forum/extend.ts
  extensions/mentions/js/src/forum/index.js
  extensions/mentions/locale/en.yml
  extensions/mentions/src/Filter/MentionedFilter.php
  framework/core/js/src/common/GambitManager.ts
  framework/core/js/src/common/helpers/highlight.tsx
  framework/core/js/src/common/query/discussions/DiscussionGambit.ts
  framework/core/js/src/common/states/PageState.ts
  framework/core/js/src/common/states/PaginatedListState.ts
  framework/core/js/src/forum/components/CommentPost.js
  framework/core/js/src/forum/components/DiscussionListItem.tsx
  framework/core/js/src/forum/components/IndexPage.tsx
  framework/core/js/src/forum/components/PostList.tsx
  framework/core/js/src/forum/components/PostListItem.tsx
  framework/core/js/src/forum/components/PostsPage.tsx
  framework/core/js/src/forum/components/PostsSearchSource.tsx
  framework/core/js/src/forum/components/PostsUserPage.tsx
  framework/core/js/src/forum/components/Search.tsx
  framework/core/js/src/forum/components/SearchModal.tsx
  framework/core/js/src/forum/routes.ts
  framework/core/js/src/forum/states/DiscussionListState.ts
  framework/core/js/src/forum/states/GlobalSearchState.ts
  framework/core/js/src/forum/states/PostListState.ts
  framework/core/less/common/Search.less
  framework/core/less/common/root.less
  framework/core/less/forum.less
  framework/core/less/forum/PostList.less
  framework/core/locale/core.yml
  framework/core/src/Api/Resource/PostResource.php
  framework/core/src/Api/Resource/UserResource.php
  framework/core/src/Discussion/Search/Filter/AuthorFilter.php
  framework/core/src/Forum/Content/Posts.php
  framework/core/src/Forum/routes.php
  framework/core/src/Post/Filter/AuthorFilter.php
  framework/core/src/Post/Filter/FulltextFilter.php
  framework/core/src/Search/SearchServiceProvider.php
  framework/core/src/User/UserRepository.php
Labels: type/feature

#3926 fix(a11y): convert empty links to buttons
  extensions/tags/js/src/forum/addTagComposer.js
  extensions/tags/less/forum.less
  framework/core/js/src/forum/components/DiscussionListItem.tsx
  framework/core/js/src/forum/components/LogInModal.tsx
  framework/core/js/src/forum/components/PostMeta.js
  framework/core/js/src/forum/components/PostStreamScrubber.js
  framework/core/js/src/forum/components/SignUpModal.tsx
  framework/core/less/common/Button.less
  framework/core/less/common/mixins.less
  framework/core/less/common/mixins/typography.less
  framework/core/less/common/scaffolding.less
  framework/core/less/forum/Post.less
  framework/core/less/forum/Scrubber.less
Labels: type/accessibility

#4020 feat: fontawesome v6
  composer.json
  framework/core/composer.json
  framework/core/less/common/Iconography.less
  framework/core/src/Frontend/Compiler/LessCompiler.php
  framework/core/src/Frontend/FrontendServiceProvider.php
Labels: type/feature

#3908 feat(emoji): allow the user to set the cdn address
  extensions/emoji/extend.php
  extensions/emoji/js/admin.js
  extensions/emoji/js/src/admin/index.js
  extensions/emoji/js/src/common/cdn.js
  extensions/emoji/js/src/forum/addComposerAutocomplete.js
  extensions/emoji/js/src/forum/cdn.js
  extensions/emoji/js/src/forum/renderEmoji.js
  extensions/emoji/locale/en.yml
Labels: type/feature

#3963 [1.x] fix: reset admin page save button in catch handler
  framework/core/js/src/admin/components/AdminPage.tsx
Labels: type/bug, javascript

#4006 Export all missing modules in compat
  extensions/emoji/js/src/forum/compat.ts
  extensions/emoji/js/src/forum/index.js
  extensions/flags/js/src/forum/compat.js
  extensions/likes/js/src/forum/compat.ts
  extensions/likes/js/src/forum/index.js
  extensions/lock/js/src/forum/compat.ts
  extensions/lock/js/src/forum/index.js
  extensions/markdown/js/src/admin/compat.ts
  extensions/markdown/js/src/admin/index.js
  extensions/markdown/js/src/common/compat.ts
  extensions/markdown/js/src/forum/compat.ts
  extensions/markdown/js/src/forum/index.js
  extensions/mentions/js/src/forum/compat.js
  extensions/nicknames/js/src/forum/compat.ts
  extensions/nicknames/js/src/forum/index.js
  extensions/package-manager/js/src/admin/compat.ts
  extensions/package-manager/js/src/admin/index.tsx
  extensions/statistics/js/src/admin/compat.ts
  extensions/statistics/js/src/admin/index.tsx
  extensions/sticky/js/src/forum/compat.ts
  extensions/sticky/js/src/forum/index.js
  extensions/subscriptions/js/src/forum/compat.ts
  extensions/subscriptions/js/src/forum/index.js
  extensions/suspend/js/src/forum/compat.js
  extensions/tags/js/src/admin/compat.js
  extensions/tags/js/src/forum/compat.js
  framework/core/js/src/admin/compat.ts
  framework/core/js/src/common/compat.ts
  framework/core/js/src/forum/compat.ts
Labels: javascript, type/extensibility

#4025 [1.x] [extensibility] feat: allow `DiscussionsSearchSource` to be extended
  framework/core/js/src/forum/compat.ts
  framework/core/js/src/forum/components/DiscussionsSearchItem.tsx
  framework/core/js/src/forum/components/DiscussionsSearchSource.tsx
Labels: javascript, type/extensibility

#4031 [1.x] [extensibility] feat: allow modifying the discussion title on PostsUserPage
  framework/core/js/src/forum/components/PostsUserPage.tsx
Labels: javascript, type/extensibility

#4030 fix: new webpack config doesn't work on windows
  js-packages/webpack-config/src/RegisterAsyncChunksPlugin.cjs
  js-packages/webpack-config/src/autoChunkNameLoader.cjs
Labels: type/regression

#4037 [1.x] [extensibility] feat: make it easier to modify AppearancePage, BasicsPage, MailPage
  framework/core/js/src/admin/components/AppearancePage.tsx
  framework/core/js/src/admin/components/BasicsPage.tsx
  framework/core/js/src/admin/components/MailPage.tsx
Labels: javascript, type/extensibility

#4038 [1.x] [QOL] chore: point fontawesome links at v5 free
  extensions/tags/js/src/admin/components/EditTagModal.tsx
  framework/core/js/src/admin/components/EditGroupModal.tsx
  framework/core/js/src/common/Application.tsx
Labels: type/cleanup, javascript

#3998 [suspend][core] [1.x] fix: suspended users can remove avatar
  extensions/suspend/extend.php
  extensions/suspend/src/Listener/PreventAvatarDeletionBySuspendedUser.php
  extensions/suspend/tests/integration/api/users/RemoveAvatarTest.php
  framework/core/src/User/Command/DeleteAvatarHandler.php
Labels: type/bug

#4036 chore: update FontAwesome v6 icon search link
  extensions/tags/js/src/admin/components/EditTagModal.tsx
  framework/core/js/src/admin/components/EditGroupModal.tsx
  framework/core/js/src/common/Application.tsx
Labels: type/cleanup

#4039 [1.x] [extensibility] chore: make WelcomeHero extensible
  framework/core/js/src/forum/components/WelcomeHero.tsx
Labels: javascript, type/extensibility

#4040 [1.x] [extensibility] chore: make PostMeta extensible
  framework/core/js/src/forum/components/PostMeta.js
Labels: javascript, type/extensibility

#4041 [1.x] [extensibility] [tags] chore: extensible TagHero
  extensions/tags/js/src/forum/components/TagHero.js
Labels: javascript, type/extensibility

#4043 [1.x] [extensibility] chore: allow extending PostPreview content
  framework/core/js/src/forum/components/PostPreview.js
Labels: javascript, type/extensibility

#4026 [1.x] [extensibility] feat: allow classes that extends `AbstractJob` to be placed on a specified queue
  extensions/mentions/src/Job/SendMentionsNotificationsJob.php
  extensions/package-manager/src/Job/ComposerCommandJob.php
  extensions/pusher/src/SendPusherNotificationsJob.php
  framework/core/src/Mail/Job/SendRawEmailJob.php
  framework/core/src/Notification/Job/SendEmailNotificationJob.php
  framework/core/src/Notification/Job/SendNotificationsJob.php
  framework/core/src/Queue/AbstractJob.php
  framework/core/src/User/Job/RequestPasswordResetJob.php
Labels: type/feature, type/extensibility

#4042 [1.x] [extensibility] feat: use common component for ip address display
  framework/core/js/src/common/compat.ts
  framework/core/js/src/common/components/IPAddress.tsx
  framework/core/js/src/forum/components/AccessTokensList.tsx
  framework/core/js/src/forum/components/PostMeta.js
Labels: javascript, type/extensibility

#4050 [1.x] [extensibility] feat: make it easier to add content after the first post
  framework/core/js/src/forum/components/PostStream.js
Labels: javascript, type/extensibility

#4045 [1.x] [extensibility] refactor(core): improve extensibility of `IndexPage`
  framework/core/js/src/forum/components/IndexPage.tsx
Labels: javascript, type/extensibility

#4046 [1.x] [extensibility] refactor(core): improve extensibility of `DiscussionPage`
  framework/core/js/src/forum/components/DiscussionPage.tsx
Labels: javascript, type/extensibility

#4048 [1.x] [extensibility] refactor(core): backport & improve extensibility of `DiscussionListItem`
  framework/core/js/src/forum/components/DiscussionListItem.tsx
Labels: javascript, type/extensibility

#4051 [1.x] fix(core): revert extensibility improvement for `replyCountItem()`
  framework/core/js/src/forum/components/DiscussionListItem.tsx
Labels: type/bug
