Repository flarum/framework, pull requests merged in 2024-11, with the labels that each got.

#4106 feat: add `fieldsBefore` and `fieldsAfter` ApiResource extenders
  framework/core/src/Extend/ApiResource.php
  framework/core/tests/integration/extenders/ApiResourceTest.php
  framework/core/tests/integration/extenders/ApiSerializerTest.php
Labels: type/extensibility

#4110 fix: cannot cast as json on mariadb 10
  framework/core/migrations/2024_05_05_000001_convert_preferences_to_json_in_users.php
  framework/core/migrations/2024_05_07_000001_convert_data_to_json_in_notifications.php
Labels: type/regression

#4117 [1.x] fix: change length of email field
  framework/core/migrations/2024_11_18_000000_increase_email_field_length.php
  framework/core/tests/integration/api/users/CreateTest.php
Labels: type/bug

#4114 [1.x] chore(core, tags): resolve `a11y` warnings in Admin Frontend
  extensions/tags/js/src/admin/components/TagsPage.js
  extensions/tags/locale/en.yml
  framework/core/js/src/admin/components/PermissionGrid.tsx
  framework/core/locale/core.yml
Labels: javascript, type/accessibility

#4116 [1.x] fix: change condition when `unread` label is shown in Scrubber
  framework/core/js/src/forum/components/PostStreamScrubber.js
Labels: type/bug, javascript

#4119 [1.x] chore: change private to protected, allowing extensibility
  framework/core/src/Forum/Auth/ResponseFactory.php
Labels: type/extensibility

#4115 feat: allow adding endpoints before/after others
  framework/core/src/Api/Endpoint/Endpoint.php
  framework/core/src/Extend/ApiResource.php
  framework/core/tests/integration/extenders/ApiResourceTest.php
Labels: type/feature

#4126 feat: recover support for ico favicon
  framework/core/src/Api/Controller/UploadFaviconController.php
  framework/core/src/Api/Controller/UploadImageController.php
  framework/core/src/Api/Controller/UploadLogoController.php
Labels: type/feature, breaking-changes

#4128 fix(regression): improve discussion list item styling extensibility
  framework/core/less/forum/DiscussionListItem.less
  framework/core/less/forum/DiscussionListPane.less
Labels: type/regression, type/extensibility

#4127 [tags] Wrong tag input width if contains CJK characters
  extensions/tags/js/src/common/components/TagSelectionModal.tsx
Labels: type/bug

#4093 fix: validate required cli install args
  framework/core/src/Install/Console/UserDataProvider.php
Labels: type/bug
