Repository flarum/framework, pull requests merged in 2024-01, with the labels that each got.

#3948 [1.x] fix: Logout controller allows open redirects
  framework/core/src/Forum/Controller/LogOutController.php
Labels: type/bug, security, prio/critical

#3955 fix: larastan changed namespace
  composer.json
  php-packages/phpstan/composer.json
  php-packages/phpstan/larastan-extension.neon
Labels: type/infrastructure

#3956 fix: ts error causing build to fail
  extensions/tags/js/src/common/states/TagListState.ts
Labels: type/cleanup

#3939 Fix width issue in edit user modal
  framework/core/js/src/common/components/EditUserModal.tsx
Labels: type/bug, type/extensibility

#3954 [2.x] fix(Mentions): allow renderer to be used without context
  extensions/mentions/src/Formatter/FormatPostMentions.php
  extensions/mentions/src/Formatter/UnparsePostMentions.php
  extensions/mentions/tests/integration/api/PostMentionsTest.php
Labels: type/bug, type/extensibility

#3947 feat: Upgrade `intervention/image` to 3.2
  composer.json
  framework/core/composer.json
  framework/core/src/Api/Controller/UploadFaviconController.php
  framework/core/src/Api/Controller/UploadImageController.php
  framework/core/src/Api/Controller/UploadLogoController.php
  framework/core/src/Filesystem/FilesystemServiceProvider.php
  framework/core/src/Foundation/InstalledSite.php
  framework/core/src/Image/ImageServiceProvider.php
  framework/core/src/User/AvatarUploader.php
  framework/core/src/User/AvatarValidator.php
  framework/core/src/User/Command/RegisterUserHandler.php
  framework/core/src/User/Command/UploadAvatarHandler.php
  framework/core/src/User/Event/AvatarSaving.php
  framework/core/tests/unit/User/AvatarUploaderTest.php
Labels: type/feature, dependencies, extension-breaking, needs-documentation

#3936 chore: use `hex_color` rule for color validation
  extensions/tags/src/TagValidator.php
  framework/core/locale/validation.yml
Labels: type/cleanup

#3961 [2.x] feat: support composer auth in workflows
  .github/workflows/REUSABLE_backend.yml
  .github/workflows/REUSABLE_frontend.yml
Labels: type/infrastructure
