Repository flarum/framework, pull requests merged in 2024-10, with the labels that each got.

#4047 [1.x] [extensibility] refactor(core, flags): improve & use extensibility of `CommentPost` & `Post`
  extensions/flags/js/src/forum/addFlagsToPosts.js
  framework/core/js/src/forum/components/CommentPost.js
  framework/core/js/src/forum/components/Post.tsx
Labels: javascript, type/extensibility

#4044 [1.x] [extensibility] Export all missing modules in compat
  extensions/akismet/js/tsconfig.json
  extensions/emoji/js/src/forum/compat.ts
  extensions/emoji/js/src/forum/index.js
  extensions/flags/js/src/forum/compat.js
  extensions/likes/js/src/forum/compat.ts
  extensions/likes/js/src/forum/index.js
  extensions/lock/js/src/forum/compat.ts
  extensions/lock/js/src/forum/index.js
  extensions/markdown/js/src/admin/compat.ts
  extensions/markdown/js/src/admin/index.js
  extensions/markdown/js/src/common/compat.ts
  extensions/markdown/js/src/forum/compat.ts
  extensions/markdown/js/src/forum/index.js
  extensions/mentions/js/src/forum/compat.js
  extensions/nicknames/js/src/forum/compat.ts
  extensions/nicknames/js/src/forum/index.js
  extensions/package-manager/js/src/admin/compat.ts
  extensions/package-manager/js/src/admin/index.tsx
  extensions/package-manager/js/tsconfig.json
  extensions/statistics/js/src/admin/compat.ts
  extensions/statistics/js/src/admin/index.tsx
  extensions/statistics/js/tsconfig.json
  extensions/sticky/js/src/forum/compat.ts
  extensions/sticky/js/src/forum/index.js
  extensions/subscriptions/js/src/forum/compat.ts
  extensions/subscriptions/js/src/forum/index.js
  extensions/suspend/js/src/forum/compat.js
  extensions/tags/js/src/admin/compat.js
  extensions/tags/js/src/forum/compat.js
  framework/core/js/src/admin/compat.ts
  framework/core/js/src/common/compat.ts
  framework/core/js/src/forum/compat.ts
Labels: javascript, type/extensibility

#4054 [1.x] [extensibility] feat: provide an 'actions' dropdown for extensions to add their additional buttons to the admin `UserListPage`
  framework/core/js/src/admin/components/UserListPage.tsx
  framework/core/locale/core.yml
Labels: javascript, type/extensibility

#4049 [1.x] [extensibility] refactor(core): allow labels of `PostStreamScrubber` to be customized
  framework/core/js/src/forum/components/PostStreamScrubber.js
Labels: javascript, type/extensibility

#4027 [1.x] [extensibility] Add (some) missing shims
  extensions/approval/js/src/@types/shims.d.ts
  extensions/likes/js/src/@types/shims.d.ts
  extensions/lock/js/src/@types/shims.d.ts
  extensions/nicknames/js/src/@types/shims.d.ts
  extensions/sticky/js/src/@types/shims.d.ts
  extensions/suspend/js/src/@types/shims.d.ts
Labels: javascript, type/extensibility

#4056 [1.x] fix: js error as guest on DiscussionListItem
  framework/core/js/src/forum/components/DiscussionListItem.tsx
Labels: type/bug, prio/critical

#4057 [1.x] fix: compat: still return controls view item, even if empty
  framework/core/js/src/forum/components/DiscussionListItem.tsx
Labels: type/bug

#4053 [1.x] feat: allow to customize time formats through translations
  framework/core/js/src/common/utils/humanTime.ts
  framework/core/js/src/forum/components/PostStream.js
  framework/core/locale/core.yml
Labels: javascript, type/extensibility

#4059 [1.x] fix(core, mentions): return null if content left empty in formatter
  extensions/mentions/src/Formatter/UnparsePostMentions.php
  extensions/mentions/src/Formatter/UnparseTagMentions.php
  extensions/mentions/src/Formatter/UnparseUserMentions.php
  extensions/mentions/tests/integration/api/CreateDiscussionTest.php
  extensions/mentions/tests/integration/api/EditPostTest.php
  framework/core/src/Formatter/Formatter.php
Labels: type/bug

#4058 chore: `1.8.6` changelog
  CHANGELOG.md
Labels: documentation

#4062 [1.x] fix: basicspage broken when no displayname drivers enabled
  framework/core/js/src/admin/components/BasicsPage.tsx
Labels: prio/critical

#4069 feat: add `List-Unsubscribe` header to emails
  framework/core/src/Mail/MailServiceProvider.php
  framework/core/src/Mail/MutateEmail.php
Labels: type/feature

#4067 refactor: remove listing of posts in the show discussion endpoint
  extensions/flags/extend.php
  extensions/likes/extend.php
  extensions/likes/tests/integration/api/ListPostsTest.php
  extensions/mentions/extend.php
  extensions/mentions/tests/integration/api/ListPostsTest.php
  extensions/tags/extend.php
  framework/core/src/Api/Resource/DiscussionResource.php
  framework/core/src/Api/Resource/PostResource.php
  framework/core/src/Api/Serializer.php
  framework/core/src/Forum/Content/Discussion.php
  framework/core/tests/integration/api/discussions/ShowTest.php
  framework/core/tests/integration/extenders/ModelVisibilityTest.php
Labels: type/cleanup, breaking-changes

#4066 feat: extension list UI
  extensions/package-manager/extend.php
  extensions/package-manager/js/src/admin/components/ControlSection.tsx
  extensions/package-manager/js/src/admin/components/DiscoverSection.tsx
  extensions/package-manager/js/src/admin/components/ExtensionCard.tsx
  extensions/package-manager/js/src/admin/components/ExtensionItem.tsx
  extensions/package-manager/js/src/admin/components/Installer.tsx
  extensions/package-manager/js/src/admin/components/MajorUpdater.tsx
  extensions/package-manager/js/src/admin/components/Pagination.tsx
  extensions/package-manager/js/src/admin/components/QueueSection.tsx
  extensions/package-manager/js/src/admin/components/SettingsPage.tsx
  extensions/package-manager/js/src/admin/components/Updater.tsx
  extensions/package-manager/js/src/admin/extend.tsx
  extensions/package-manager/js/src/admin/index.tsx
  extensions/package-manager/js/src/admin/models/ExternalExtension.ts
  extensions/package-manager/js/src/admin/states/ExtensionListState.ts
  extensions/package-manager/js/src/admin/states/ExtensionManagerState.ts
  extensions/package-manager/js/src/admin/states/QueueState.ts
  extensions/package-manager/less/admin.less
  extensions/package-manager/less/admin/ControlSection.less
  extensions/package-manager/less/admin/DiscoverSection.less
  extensions/package-manager/less/admin/ExtensionCard.less
  extensions/package-manager/locale/en.yml
  extensions/package-manager/src/Api/Resource/ExternalExtensionResource.php
  extensions/package-manager/src/Api/Resource/TaskResource.php
  extensions/package-manager/src/Api/Schema/SortColumn.php
  extensions/package-manager/src/Command/CheckForUpdatesHandler.php
  extensions/package-manager/src/Command/RequireExtensionHandler.php
  extensions/package-manager/src/Composer/ComposerJson.php
  extensions/package-manager/src/Exception/CannotFetchExternalExtension.php
  extensions/package-manager/src/Extension/ExtensionUtils.php
  extensions/package-manager/src/External/Extension.php
  extensions/package-manager/src/External/RequestWrapper.php
  extensions/package-manager/src/Support/Util.php
  extensions/package-manager/tests/integration/TestCase.php
  extensions/tags/tests/integration/api/tags/ListTest.php
  framework/core/js/src/admin/AdminApplication.tsx
  framework/core/js/src/admin/components/UserListPage.tsx
  framework/core/js/src/common/Store.ts
  framework/core/js/src/common/common.ts
  framework/core/js/src/common/components/Input.tsx
  framework/core/js/src/common/components/Pagination.tsx
  framework/core/js/src/common/components/SearchModal.tsx
  framework/core/js/src/common/states/PaginatedListState.ts
  framework/core/js/src/common/utils/formatAmount.ts
  framework/core/less/admin/ExtensionPage.less
  framework/core/less/admin/UsersListPage.less
  framework/core/less/common/Alert.less
  framework/core/less/common/Badge.less
  framework/core/less/common/Form.less
  framework/core/less/common/FormControl.less
  framework/core/less/common/Pagination.less
  framework/core/less/common/Search.less
  framework/core/less/common/Tabs.less
  framework/core/less/common/common.less
  framework/core/less/common/scaffolding.less
  framework/core/less/common/variables.less
  framework/core/src/Api/Endpoint/Index.php
  framework/core/src/Api/Resource/AbstractDatabaseResource.php
  framework/core/src/Extension/Extension.php
Labels: type/feature, javascript

#4073 feat: add option for filtering read stickied on all discussions page
  extensions/sticky/extend.php
  extensions/sticky/js/src/admin/extend.tsx
  extensions/sticky/locale/en.yml
  extensions/sticky/src/PinStickiedDiscussionsToTop.php
  extensions/sticky/tests/integration/api/ListDiscussionsTest.php
Labels: type/feature

#3935 feat: allow resetting settings to default
  framework/core/src/Api/Controller/SetSettingsController.php
  framework/core/src/Extend/Settings.php
  framework/core/tests/integration/extenders/SettingsTest.php
Labels: type/extensibility

#4021 chore: fix typos
  .github/ISSUE_TEMPLATE/bug-report.yml
  CHANGELOG.md
  extensions/package-manager/locale/en.yml
  extensions/package-manager/src/Command/CheckForUpdatesHandler.php
  extensions/package-manager/tests/integration/api/extensions/RemoveExtensionTest.php
  extensions/package-manager/tests/integration/api/extensions/RequireExtensionTest.php
  extensions/subscriptions/locale/en.yml
  extensions/tags/CHANGELOG.md
  framework/core/js/src/common/ExportRegistry.ts
  framework/core/js/src/common/app.ts
  framework/core/js/src/common/resolvers/DefaultResolver.tsx
  framework/core/js/src/common/utils/styleSelectedText.ts
  framework/core/js/src/forum/components/DiscussionListPane.js
  framework/core/js/src/forum/components/PostStreamScrubber.js
  framework/core/js/src/forum/resolvers/DiscussionPageResolver.ts
  framework/core/js/src/forum/states/GlobalSearchState.ts
  framework/core/js/src/forum/utils/slidable.js
  framework/core/locale/core.yml
  framework/core/src/Extend/Theme.php
  framework/core/src/Foundation/ContainerUtil.php
  framework/core/src/Mail/FlarumLogTransport.php
  framework/core/src/Notification/NotificationMailer.php
  framework/core/tests/integration/api/discussions/ListWithFulltextSearchTest.php
  framework/core/tests/integration/extenders/ApiSerializerTest.php
  framework/core/tests/integration/extenders/SearchDriverTest.php
  framework/core/tests/integration/extenders/ServiceProviderTest.php
  framework/core/tests/integration/extenders/ValidatorTest.php
  php-packages/phpstan/phpstan-baseline.neon
Labels: type/cleanup

#3951 fix: use dynamic viewport units for height of Modals
  framework/core/less/common/Modal.less
Labels: type/bug

#4016 feat(sticky): make excerpt optional in sticky
  extensions/sticky/extend.php
  extensions/sticky/js/src/admin/extend.tsx
  extensions/sticky/js/src/forum/addStickyExcerpt.js
  extensions/sticky/locale/en.yml
Labels: type/feature

#4072 chore: ignore deprecation errors in prod
  framework/core/src/Foundation/Site.php
Labels: type/cleanup

#4083 [1.x] fix new search term not being passed
  framework/core/js/src/forum/components/DiscussionsSearchSource.tsx
Labels: type/bug, prio/high

#4085 [1.x] fix: postfooter did not apply the empty subclass
  framework/core/js/src/forum/components/Post.tsx
Labels: type/bug, type/regression

#4074 fix: usage of aria-hidden=false might cause inconsistent behavior
  framework/core/js/src/admin/components/UserListPage.tsx
  framework/core/js/src/common/components/ModalManager.tsx
Labels: type/accessibility

#3748 chore(mentions): add integration test for reply approval notification
  extensions/mentions/composer.json
  extensions/mentions/tests/integration/api/NotificationsTest.php
Labels: type/infrastructure

#4004 feat(nicknames): allow OAuth to provide a nickname
  extensions/nicknames/js/src/forum/index.js
Labels: type/feature

#4029 feat: date time formats from locales
  framework/core/js/src/admin/components/UserListPage.tsx
  framework/core/js/src/common/Translator.tsx
  framework/core/js/src/common/helpers/fullTime.tsx
  framework/core/js/src/common/helpers/humanTime.tsx
  framework/core/js/src/common/utils/humanTime.ts
  framework/core/js/src/common/utils/liveHumanTimes.ts
  framework/core/js/src/forum/components/PostStream.js
  framework/core/locale/core.yml
Labels: type/bug, type/feature

#4088 chore: switch formatter to `format-message`
  framework/core/js/package.json
  framework/core/js/src/@types/translator-icu-rich.d.ts
  framework/core/js/src/@types/translator-icu.d.ts
  framework/core/js/src/common/Translator.tsx
  framework/core/js/src/common/helpers/fireDebugWarning.ts
  framework/core/js/src/common/utils/abbreviateNumber.ts
  framework/core/js/src/forum/components/AccessTokensList.tsx
  framework/core/js/tests/unit/common/utils/Translator.test.ts
  framework/core/tests/unit/Locale/TranslatorTest.php
  js-packages/jest-config/src/boostrap/common.js
  yarn.lock
Labels: type/bug

#4089 Fix app header container overflow on mobile
  framework/core/less/common/App.less
Labels: type/regression

#4097 [1.x] fix: resolve regression in TS typing errors
  extensions/approval/js/src/@types/shims.d.ts
  extensions/flags/js/src/@types/shims.d.ts
  extensions/likes/js/src/@types/shims.d.ts
  extensions/lock/js/src/@types/shims.d.ts
  extensions/mentions/js/src/@types/shims.d.ts
  extensions/nicknames/js/src/@types/shims.d.ts
  extensions/sticky/js/src/@types/shims.d.ts
  extensions/suspend/js/src/@types/shims.d.ts
  extensions/tags/js/src/@types/shims.d.ts
Labels: type/regression, type/extensibility
