Repository flarum/framework, pull requests merged in 2025-02, with the labels that each got.

#4176 [1.x] fix(em): skip incompatible extension updates
  extensions/package-manager/src/Command/CheckForUpdatesHandler.php
  extensions/package-manager/src/Support/Util.php
Labels: type/bug

#4175 feat(pm): messages anchor link
  extensions/messages/extend.php
  extensions/messages/js/@types/shims.d.ts
  extensions/messages/js/src/admin/extend.ts
  extensions/messages/js/src/common/models/DialogMessage.ts
  extensions/messages/js/src/forum/components/DialogSection.tsx
  extensions/messages/js/src/forum/components/Message.tsx
  extensions/messages/js/src/forum/components/MessageStream.tsx
  extensions/messages/js/src/forum/extend.ts
  extensions/messages/js/src/forum/states/MessageStreamState.ts
  extensions/messages/locale/en.yml
  extensions/messages/migrations/2025_01_31_000000_add_number_to_dialog_messages.php
  extensions/messages/src/Api/Resource/DialogMessageResource.php
  extensions/messages/src/DialogMessage.php
  extensions/messages/tests/integration/api/ListTest.php
  extensions/messages/tests/integration/api/dialog_messages/CreateTest.php
  extensions/messages/tests/integration/api/dialogs/UpdateTest.php
  framework/core/js/src/common/states/PaginatedListState.ts
  framework/core/src/Api/Endpoint/Index.php
  framework/core/tests/integration/api/groups/ListTest.php
Labels: type/feature

#4177 fix(em): skip incompatible extension updates
  extensions/package-manager/src/Command/CheckForUpdatesHandler.php
  extensions/package-manager/src/Support/Util.php
Labels: type/bug

#4180 feat(pm): delete own messages
  extensions/messages/extend.php
  extensions/messages/js/src/admin/extend.ts
  extensions/messages/js/src/admin/extend.tsx
  extensions/messages/js/src/common/extend.ts
  extensions/messages/js/src/common/models/DialogMessage.ts
  extensions/messages/js/src/forum/components/Message.tsx
  extensions/messages/js/src/forum/components/MessageStream.tsx
  extensions/messages/js/src/forum/utils/MessageControls.tsx
  extensions/messages/locale/en.yml
  extensions/messages/src/Access/DialogMessagePolicy.php
  extensions/messages/src/Api/Resource/DialogMessageResource.php
  framework/core/js/src/admin/components/SettingDropdown.tsx
  framework/core/js/src/common/states/PaginatedListState.ts
  framework/core/js/src/forum/utils/PostControls.js
Labels: type/feature

#4182 refactor(core): improve extensibility of `IndexPage`
  framework/core/js/src/forum/components/IndexPage.tsx
Labels: javascript, type/extensibility

#4183 fix(core): return empty object if selected mail driver is unavailable
  framework/core/js/src/admin/components/MailPage.tsx
Labels: type/bug

#4184 fix(core, tags): resolve `a11y` warnings in Admin Frontend
  extensions/tags/js/src/admin/components/TagsPage.js
  extensions/tags/locale/en.yml
  framework/core/js/src/admin/components/PermissionGrid.tsx
  framework/core/js/src/common/components/Pagination.tsx
  framework/core/locale/core.yml
Labels: type/accessibility

#4185 fix(core): change condition when `unread` label is shown in Scrubber
  framework/core/js/src/forum/components/PostStreamScrubber.js
Labels: type/bug

#4187 feat: reusable component for showing IP address
  framework/core/js/src/common/components/IPAddress.tsx
  framework/core/js/src/forum/components/AccessTokensList.tsx
  framework/core/js/src/forum/components/PostMeta.tsx
Labels: type/extensibility

#4186 feat: make it easier to add content after the first post
  framework/core/js/src/forum/components/PostStream.js
Labels: type/extensibility

#4188 feat: actions dropdown in admin user list
  framework/core/js/src/admin/components/UserListPage.tsx
  framework/core/locale/core.yml
Labels: type/extensibility

#4196 refactor(core): improve extensibility of `PostMeta` component
  framework/core/js/src/forum/components/PostMeta.tsx
Labels: type/extensibility

#4197 feat: allow extending `PostPreview` content
  framework/core/js/src/forum/components/PostPreview.js
Labels: type/extensibility

#4198 feat(tags): improve extensibility of `TagHero`
  extensions/tags/js/src/forum/components/TagHero.js
Labels: type/extensibility

#4199 feat: improve extensibility of `WelcomeHero`
  framework/core/js/src/forum/components/WelcomeHero.tsx
Labels: type/extensibility
